import {
  Member,
  Visitor,
  ChurchService,
  AttendanceRecord,
  HeadcountRecord,
  GivingRecord,
  PledgeRecord,
  PledgeCampaign,
  ExpenseRecord,
  Ministry,
  SmallGroup,
  ChurchEvent,
  PastoralCareRecord,
  PrayerRequest,
  CommunicationRecord,
  AuditLog,
  ChurchSettings,
  UserProfile,
  WelfareContribution,
  WelfareClaim,
  ChildCheckInRecord,
  ChurchAsset,
  RosterAssignment,
  FoundationCohort,
  FoundationStudent,
} from '../types/database.types';

export const initialSettings: ChurchSettings = {
  church_name: 'Greater Works City Church',
  branch_name: 'City of Refuge - Joma Central',
  tagline: 'Exceeding Abundantly Above All We Ask or Think (Ephesians 3:20)',
  short_name: 'GWCC',
  senior_pastor: 'Prophet Elisha K. Richard',
  general_secretary: 'Tamekloe Clara Gaewornu',
  logo_url: '/assets/logo.png',
  location: 'Joma New Site, Greater Accra, Ghana',
  address: 'Off Ablekuma-Joma Highway, Joma New Site',
  gps_address: 'GA-183-4921',
  phone: '+233 24 412 3456',
  email: 'info@greaterworkscitychurch.org',
  currency: 'GHS',
  currency_symbol: 'GH₵',
  timezone: 'Africa/Accra',
};

export const sampleUsers: UserProfile[] = [
  {
    id: 'usr-1',
    first_name: 'Elisha',
    last_name: 'Richard',
    email: 'prophet@greaterworkscitychurch.org',
    phone: '+233 24 412 3456',
    department: 'Pastoral Council',
    role: 'senior_pastor',
    is_active: true,
    created_at: '2025-01-01T08:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'usr-2',
    first_name: 'Clara',
    last_name: 'Gaewornu',
    email: 'secretary@greaterworkscitychurch.org',
    phone: '+233 20 890 1234',
    department: 'Church Administration',
    role: 'administrator',
    is_active: true,
    created_at: '2025-01-01T08:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'usr-3',
    first_name: 'Emmanuel',
    last_name: 'Osei',
    email: 'pastor.osei@greaterworkscitychurch.org',
    phone: '+233 24 987 6543',
    department: 'Pastoral Care & Music',
    role: 'pastor',
    is_active: true,
    created_at: '2025-01-01T08:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'usr-4',
    first_name: 'Akosua',
    last_name: 'Frimpong',
    email: 'finance@greaterworkscitychurch.org',
    phone: '+233 27 555 4321',
    department: 'Finance & Accounts',
    role: 'finance_officer',
    is_active: true,
    created_at: '2025-01-05T08:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'usr-5',
    first_name: 'Kwame',
    last_name: 'Mensah',
    email: 'ushering@greaterworkscitychurch.org',
    phone: '+233 24 333 8899',
    department: 'Ushers & Protocol',
    role: 'attendance_officer',
    is_active: true,
    created_at: '2025-02-01T08:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
  },
];

export const sampleMinistries: Ministry[] = [
  {
    id: 'min-1',
    name: 'Voice of Grace (Choir & Music)',
    description: 'Lead the congregation in prophetic praise, deep worship, and choral ministrations.',
    leader_name: 'Pastor Emmanuel Osei',
    meeting_schedule: 'Every Saturday at 4:00 PM',
    meeting_day: 'Saturday',
    meeting_time: '16:00',
    status: 'active',
    member_count: 24,
  },
  {
    id: 'min-2',
    name: "King's Ushers & Protocol",
    description: 'Ensure orderly sanctuary flow, warm visitor reception, and dignitary protocol during all church gatherings.',
    leader_name: 'Brother Kwame Mensah',
    meeting_schedule: 'Every Saturday at 5:30 PM',
    meeting_day: 'Saturday',
    meeting_time: '17:30',
    status: 'active',
    member_count: 18,
  },
  {
    id: 'min-3',
    name: 'Sound, Media & Broadcast',
    description: 'Sound engineering, live streaming on social platforms, digital recording, and multimedia projection.',
    leader_name: 'Brother Benjamin Antwi',
    meeting_schedule: 'Every Saturday at 3:00 PM',
    meeting_day: 'Saturday',
    meeting_time: '15:00',
    status: 'active',
    member_count: 12,
  },
  {
    id: 'min-4',
    name: "Kingdom Builders (Men's Fellowship)",
    description: 'Empowering Christian men through business mentorship, family leadership, and kingdom financing.',
    leader_name: 'Elder Kofi Addo',
    meeting_schedule: '1st Saturday of each month at 7:00 AM',
    meeting_day: 'Saturday',
    meeting_time: '07:00',
    status: 'active',
    member_count: 35,
  },
  {
    id: 'min-5',
    name: 'Virtuous Women Fellowship',
    description: 'Nurturing godly women, mothers, and young ladies in prayer, home building, and community charity.',
    leader_name: 'Deaconess Akosua Frimpong',
    meeting_schedule: '2nd Saturday of each month at 8:00 AM',
    meeting_day: 'Saturday',
    meeting_time: '08:00',
    status: 'active',
    member_count: 42,
  },
  {
    id: 'min-6',
    name: 'Chosen Generation (Youth & Campus)',
    description: 'Dynamic ministry for senior high, tertiary students, and young professionals discovering their destiny.',
    leader_name: 'Sister Abena Serwaa',
    meeting_schedule: 'Every Sunday at 1:00 PM',
    meeting_day: 'Sunday',
    meeting_time: '13:00',
    status: 'active',
    member_count: 38,
  },
  {
    id: 'min-7',
    name: 'Little Lights (Children & Sunday School)',
    description: 'Biblical foundation, creative arts, and age-graded Bible lessons for toddlers and young children.',
    leader_name: 'Sister Grace Ansah',
    meeting_schedule: 'Every Sunday during Main Service (8:30 AM)',
    meeting_day: 'Sunday',
    meeting_time: '08:30',
    status: 'active',
    member_count: 45,
  },
  {
    id: 'min-8',
    name: 'Evangelism & Welfare Outreach',
    description: 'Hospital visits, street evangelism, prison ministry, and welfare support for needy families.',
    leader_name: 'Brother Samuel Tetteh',
    meeting_schedule: '3rd Saturday of each month at 6:30 AM',
    meeting_day: 'Saturday',
    meeting_time: '06:30',
    status: 'active',
    member_count: 22,
  },
];

export const sampleSmallGroups: SmallGroup[] = [
  {
    id: 'sg-1',
    name: 'Joma Central Cell',
    leader_name: 'Elder Kofi Addo',
    leader_phone: '+233 24 111 2233',
    meeting_location: "Elder Kofi's Residence, Joma New Site",
    zone: 'Zone 1 - Joma Central',
    meeting_day: 'Tuesday',
    meeting_time: '18:30',
    member_count: 16,
  },
  {
    id: 'sg-2',
    name: 'Ablekuma Highway Fellowship',
    leader_name: 'Deaconess Akosua Frimpong',
    leader_phone: '+233 27 555 4321',
    meeting_location: 'Near Ablekuma Curve, Behind Fuel Station',
    zone: 'Zone 2 - Ablekuma Corridor',
    meeting_day: 'Tuesday',
    meeting_time: '19:00',
    member_count: 14,
  },
  {
    id: 'sg-3',
    name: 'Weija Hilltop Cell',
    leader_name: 'Brother Benjamin Antwi',
    leader_phone: '+233 24 777 6655',
    meeting_location: 'Weija Barrier Junction area',
    zone: 'Zone 3 - Weija & SCC',
    meeting_day: 'Tuesday',
    meeting_time: '18:30',
    member_count: 12,
  },
  {
    id: 'sg-4',
    name: 'Anyaa Market Fellowship',
    leader_name: 'Sister Abena Serwaa',
    leader_phone: '+233 20 333 4455',
    meeting_location: 'Anyaa Last Stop, Opposite Clinic',
    zone: 'Zone 4 - Anyaa & Awoshie',
    meeting_day: 'Tuesday',
    meeting_time: '19:00',
    member_count: 15,
  },
  {
    id: 'sg-5',
    name: 'Agape Home Fellowship',
    leader_name: 'Brother Samuel Tetteh',
    leader_phone: '+233 24 999 1122',
    meeting_location: 'Joma Top Town, Near Water Tower',
    zone: 'Zone 1 - Joma Central',
    meeting_day: 'Thursday',
    meeting_time: '18:30',
    member_count: 10,
  },
];

export const sampleServices: ChurchService[] = [
  {
    id: 'srv-1',
    name: 'Sunday Prophetic Celebration Service',
    type: 'sunday',
    day_of_week: 'Sunday',
    start_time: '08:30',
    end_time: '11:45',
    venue: 'City of Refuge Main Sanctuary, Joma',
    service_leader: 'Prophet Elisha K. Richard',
    preacher: 'Prophet Elisha K. Richard',
    worship_leader: 'Pastor Emmanuel Osei',
    expected_attendance: 250,
    description: 'Our flagship weekly celebration with deep prophetic praise, revelation preaching, healing, and prophetic declarations.',
    is_active: true,
  },
  {
    id: 'srv-2',
    name: 'Midweek Miracle & Breakthrough Encounter',
    type: 'midweek',
    day_of_week: 'Wednesday',
    start_time: '18:30',
    end_time: '20:30',
    venue: 'City of Refuge Main Sanctuary, Joma',
    service_leader: 'Pastor Emmanuel Osei',
    preacher: 'Prophet Elisha K. Richard',
    worship_leader: 'Sister Abena Serwaa',
    expected_attendance: 140,
    description: 'Intense teaching of the Word, practical faith warfare, communion, and special prayer ministration for believers.',
    is_active: true,
  },
  {
    id: 'srv-3',
    name: 'Prophetic Hour & All-Night Vigil',
    type: 'prayer',
    day_of_week: 'Friday',
    start_time: '22:00',
    end_time: '04:00',
    venue: 'City of Refuge Main Sanctuary, Joma',
    service_leader: 'Prophet Elisha K. Richard',
    preacher: 'Prophet Elisha K. Richard',
    worship_leader: 'Voice of Grace Praise Team',
    expected_attendance: 180,
    description: 'High-voltage night of intercession, spiritual warfare, family deliverance, and open heavens.',
    is_active: true,
  },
];

export const sampleMembers: Member[] = [
  {
    id: 'mem-1',
    member_id: 'GWCC-0001',
    tithe_number: 'T-1001',
    first_name: 'Kwame',
    last_name: 'Mensah',
    gender: 'male',
    date_of_birth: '1984-04-12',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Logistics Supervisor',
    employer: 'Accra Port Terminal Ltd',
    phone: '+233 24 333 8899',
    email: 'kwame.mensah@gmail.com',
    residential_address: 'House 42, Joma New Site',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-183-4901',
    status: 'leader',
    membership_date: '2023-01-15',
    baptism_status: true,
    baptism_date: '2023-03-20',
    baptized_by: 'Prophet Elisha K. Richard',
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-2',
    ministry_name: "King's Ushers & Protocol",
    small_group_id: 'sg-1',
    small_group_name: 'Joma Central Cell',
    leadership_position: 'Head of Protocol',
    spouse_name: 'Faustina Mensah',
    spouse_is_member: true,
    number_of_children: 3,
    national_id: 'GHA-712398412-1',
    preferred_communication: 'whatsapp',
    is_archived: false,
    created_at: '2023-01-15T10:00:00.000Z',
    updated_at: '2026-01-15T10:00:00.000Z',
  },
  {
    id: 'mem-2',
    member_id: 'GWCC-0002',
    tithe_number: 'T-1002',
    first_name: 'Akosua',
    last_name: 'Frimpong',
    gender: 'female',
    date_of_birth: '1988-09-23',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Chartered Accountant',
    employer: 'Universal Merchant Services',
    phone: '+233 27 555 4321',
    email: 'akosua.frimpong@outlook.com',
    residential_address: 'Plot 15, Ablekuma Highway',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-184-1122',
    status: 'leader',
    membership_date: '2023-02-10',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-5',
    ministry_name: 'Virtuous Women Fellowship',
    small_group_id: 'sg-2',
    small_group_name: 'Ablekuma Highway Fellowship',
    leadership_position: 'Finance Deaconess',
    spouse_name: 'Kwabena Frimpong',
    number_of_children: 2,
    national_id: 'GHA-829103841-4',
    preferred_communication: 'whatsapp',
    is_archived: false,
    created_at: '2023-02-10T10:00:00.000Z',
    updated_at: '2026-02-01T10:00:00.000Z',
  },
  {
    id: 'mem-3',
    member_id: 'GWCC-0003',
    tithe_number: 'T-1003',
    first_name: 'Kofi',
    last_name: 'Addo',
    gender: 'male',
    date_of_birth: '1976-11-05',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Civil Contractor',
    employer: 'Addo Infrastructure Ltd',
    phone: '+233 24 111 2233',
    email: 'elder.kofi.addo@gmail.com',
    residential_address: 'Near Old Chief Palace, Joma',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-183-5509',
    status: 'leader',
    membership_date: '2022-11-01',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-4',
    ministry_name: "Kingdom Builders (Men's Fellowship)",
    small_group_id: 'sg-1',
    small_group_name: 'Joma Central Cell',
    leadership_position: 'Presiding Elder',
    spouse_name: 'Evelyn Addo',
    spouse_is_member: true,
    number_of_children: 4,
    national_id: 'GHA-629104921-7',
    preferred_communication: 'call',
    is_archived: false,
    created_at: '2022-11-01T10:00:00.000Z',
    updated_at: '2026-01-20T10:00:00.000Z',
  },
  {
    id: 'mem-4',
    member_id: 'GWCC-0004',
    tithe_number: 'T-1004',
    first_name: 'Abena',
    last_name: 'Serwaa',
    gender: 'female',
    date_of_birth: '1995-07-18',
    marital_status: 'single',
    nationality: 'Ghanaian',
    occupation: 'Pharmacist',
    employer: 'Ridge Care Pharmacy, Anyaa',
    phone: '+233 20 333 4455',
    email: 'abena.serwaa@yahoo.com',
    residential_address: 'House 8B, Anyaa Market Road',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-190-2810',
    status: 'active',
    membership_date: '2023-04-14',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-6',
    ministry_name: 'Chosen Generation (Youth & Campus)',
    small_group_id: 'sg-4',
    small_group_name: 'Anyaa Market Fellowship',
    leadership_position: 'Youth President',
    national_id: 'GHA-910293849-0',
    preferred_communication: 'whatsapp',
    is_archived: false,
    created_at: '2023-04-14T10:00:00.000Z',
    updated_at: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'mem-5',
    member_id: 'GWCC-0005',
    tithe_number: 'T-1005',
    first_name: 'Benjamin',
    last_name: 'Antwi',
    gender: 'male',
    date_of_birth: '1992-02-28',
    marital_status: 'single',
    nationality: 'Ghanaian',
    occupation: 'Software & Network Engineer',
    employer: 'FinTech Hub Ghana',
    phone: '+233 24 777 6655',
    email: 'ben.antwi@techghana.com',
    residential_address: 'Hilltop View, Weija',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-210-9831',
    status: 'leader',
    membership_date: '2023-03-12',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-3',
    ministry_name: 'Sound, Media & Broadcast',
    small_group_id: 'sg-3',
    small_group_name: 'Weija Hilltop Cell',
    leadership_position: 'Media Director',
    national_id: 'GHA-789012345-2',
    preferred_communication: 'whatsapp',
    is_archived: false,
    created_at: '2023-03-12T10:00:00.000Z',
    updated_at: '2026-02-15T10:00:00.000Z',
  },
  {
    id: 'mem-6',
    member_id: 'GWCC-0006',
    tithe_number: 'T-1006',
    first_name: 'Grace',
    last_name: 'Ansah',
    gender: 'female',
    date_of_birth: '1989-12-14',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Senior High School Teacher',
    employer: 'Ghana Education Service',
    phone: '+233 50 123 9876',
    email: 'grace.ansah@gmail.com',
    residential_address: 'Estate Junction, Joma',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-183-6621',
    status: 'active',
    membership_date: '2023-05-20',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-7',
    ministry_name: 'Little Lights (Children & Sunday School)',
    small_group_id: 'sg-1',
    small_group_name: 'Joma Central Cell',
    leadership_position: 'Children Ministry Coordinator',
    spouse_name: 'Michael Ansah',
    number_of_children: 2,
    national_id: 'GHA-890123456-7',
    preferred_communication: 'sms',
    is_archived: false,
    created_at: '2023-05-20T10:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'mem-7',
    member_id: 'GWCC-0007',
    tithe_number: 'T-1007',
    first_name: 'Samuel',
    last_name: 'Tetteh',
    gender: 'male',
    date_of_birth: '1982-06-30',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Wholesale Food Merchant',
    employer: 'Self Employed',
    phone: '+233 24 999 1122',
    email: 'samuel.tetteh@tettehtrading.com',
    residential_address: 'Behind Joma Water Works',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-183-7744',
    status: 'leader',
    membership_date: '2023-06-08',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-8',
    ministry_name: 'Evangelism & Welfare Outreach',
    small_group_id: 'sg-5',
    small_group_name: 'Agape Home Fellowship',
    leadership_position: 'Outreach Director',
    spouse_name: 'Patience Tetteh',
    number_of_children: 3,
    national_id: 'GHA-678901234-5',
    preferred_communication: 'call',
    is_archived: false,
    created_at: '2023-06-08T10:00:00.000Z',
    updated_at: '2026-02-28T10:00:00.000Z',
  },
  {
    id: 'mem-8',
    member_id: 'GWCC-0008',
    tithe_number: 'T-1008',
    first_name: 'Faustina',
    last_name: 'Mensah',
    gender: 'female',
    date_of_birth: '1987-03-15',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Registered Midwife',
    employer: 'Ga South Municipal Hospital',
    phone: '+233 20 444 7711',
    email: 'faustina.mensah@gmail.com',
    residential_address: 'House 42, Joma New Site',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-183-4901',
    status: 'active',
    membership_date: '2023-01-15',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-5',
    ministry_name: 'Virtuous Women Fellowship',
    small_group_id: 'sg-1',
    small_group_name: 'Joma Central Cell',
    spouse_name: 'Kwame Mensah',
    spouse_is_member: true,
    number_of_children: 3,
    national_id: 'GHA-789123450-8',
    preferred_communication: 'whatsapp',
    is_archived: false,
    created_at: '2023-01-15T10:00:00.000Z',
    updated_at: '2026-01-15T10:00:00.000Z',
  },
  {
    id: 'mem-9',
    member_id: 'GWCC-0009',
    tithe_number: 'T-1009',
    first_name: 'David',
    last_name: 'Quaye',
    gender: 'male',
    date_of_birth: '1997-10-10',
    marital_status: 'single',
    nationality: 'Ghanaian',
    occupation: 'Graphic Designer & Videographer',
    employer: 'Creative Pixels Studio',
    phone: '+233 54 888 3322',
    email: 'dquaye.art@gmail.com',
    residential_address: 'Ablekuma Fan Milk Junction',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-184-7733',
    status: 'active',
    membership_date: '2024-01-21',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-3',
    ministry_name: 'Sound, Media & Broadcast',
    small_group_id: 'sg-2',
    small_group_name: 'Ablekuma Highway Fellowship',
    national_id: 'GHA-923456781-3',
    preferred_communication: 'whatsapp',
    is_archived: false,
    created_at: '2024-01-21T10:00:00.000Z',
    updated_at: '2026-02-10T10:00:00.000Z',
  },
  {
    id: 'mem-10',
    member_id: 'GWCC-0010',
    tithe_number: 'T-1010',
    first_name: 'Joyce',
    last_name: 'Boakye',
    gender: 'female',
    date_of_birth: '1993-08-04',
    marital_status: 'single',
    nationality: 'Ghanaian',
    occupation: 'Nurse Officer',
    employer: 'Korle Bu Polyclinic',
    phone: '+233 27 666 9900',
    email: 'joyce.boakye93@gmail.com',
    residential_address: 'SCC Barrier Area, Weija',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-210-4411',
    status: 'active',
    membership_date: '2024-03-10',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-1',
    ministry_name: 'Voice of Grace (Choir & Music)',
    small_group_id: 'sg-3',
    small_group_name: 'Weija Hilltop Cell',
    national_id: 'GHA-834567890-2',
    preferred_communication: 'whatsapp',
    is_archived: false,
    created_at: '2024-03-10T10:00:00.000Z',
    updated_at: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'mem-11',
    member_id: 'GWCC-0011',
    tithe_number: 'T-1011',
    first_name: 'Emmanuel',
    last_name: 'Osei',
    gender: 'male',
    date_of_birth: '1980-05-19',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Associate Pastor / Music Director',
    employer: 'Greater Works City Church',
    phone: '+233 24 987 6543',
    email: 'pastor.osei@greaterworkscitychurch.org',
    residential_address: 'Pastoral Residence, Joma',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-183-4921',
    status: 'leader',
    membership_date: '2022-09-01',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-1',
    ministry_name: 'Voice of Grace (Choir & Music)',
    small_group_id: 'sg-1',
    small_group_name: 'Joma Central Cell',
    leadership_position: 'Associate Pastor & Music Director',
    spouse_name: 'Doris Osei',
    spouse_is_member: true,
    number_of_children: 3,
    national_id: 'GHA-610293847-5',
    preferred_communication: 'whatsapp',
    is_archived: false,
    created_at: '2022-09-01T10:00:00.000Z',
    updated_at: '2026-01-01T10:00:00.000Z',
  },
  {
    id: 'mem-12',
    member_id: 'GWCC-0012',
    tithe_number: 'T-1012',
    first_name: 'Clara',
    last_name: 'Gaewornu',
    gender: 'female',
    date_of_birth: '1986-11-25',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'General Secretary & Administrator',
    employer: 'Greater Works City Church',
    phone: '+233 20 890 1234',
    email: 'secretary@greaterworkscitychurch.org',
    residential_address: 'Gaewornu Villa, Joma New Site',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-183-4950',
    status: 'leader',
    membership_date: '2022-08-15',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-2',
    ministry_name: "King's Ushers & Protocol",
    small_group_id: 'sg-1',
    small_group_name: 'Joma Central Cell',
    leadership_position: 'General Secretary',
    spouse_name: 'Kafui Gaewornu',
    number_of_children: 2,
    national_id: 'GHA-723456789-1',
    preferred_communication: 'whatsapp',
    is_archived: false,
    created_at: '2022-08-15T10:00:00.000Z',
    updated_at: '2026-01-05T10:00:00.000Z',
  },
];

export const sampleVisitors: Visitor[] = [
  {
    id: 'vis-1',
    full_name: 'Prince Daniel Kwarteng',
    gender: 'male',
    phone: '+233 55 123 7890',
    email: 'pkwarteng@gmail.com',
    address: 'Near Joma Taxi Rank',
    gps_address: 'GA-183-8812',
    visit_date: '2026-09-27',
    service_attended: 'Sunday Prophetic Celebration Service',
    invited_by: 'Brother Kwame Mensah',
    how_heard: 'Friend / Church Member',
    prayer_request: 'Breakthrough in interview for international maritime logistics job.',
    follow_up_status: 'returning_visitor',
    assigned_to: 'usr-5',
    assigned_to_name: 'Kwame Mensah',
    notes: 'Warm gentleman. Attended second service with enthusiasm. Expressed interest in joining the Protocol team.',
    created_at: '2026-09-27T12:00:00.000Z',
    updated_at: '2026-09-30T10:00:00.000Z',
  },
  {
    id: 'vis-2',
    full_name: 'Rita Serwaa Boateng',
    gender: 'female',
    phone: '+233 24 666 1234',
    email: 'rita.boateng@yahoo.com',
    address: 'Ablekuma Fan Milk, Near Shell',
    gps_address: 'GA-184-3321',
    visit_date: '2026-09-27',
    service_attended: 'Sunday Prophetic Celebration Service',
    invited_by: 'Church Banner along Highway',
    how_heard: 'Flyer / Banner',
    prayer_request: 'Divine healing for chronic migraines and peace in marriage.',
    follow_up_status: 'contacted',
    assigned_to: 'usr-4',
    assigned_to_name: 'Akosua Frimpong',
    notes: 'Contacted via WhatsApp on Tuesday. She appreciated the prayer and requested home visitation from Virtuous Women.',
    created_at: '2026-09-27T12:15:00.000Z',
    updated_at: '2026-09-29T14:30:00.000Z',
  },
  {
    id: 'vis-3',
    full_name: 'Joshua Nii Armah',
    gender: 'male',
    phone: '+233 20 777 9988',
    address: 'Weija SCC Junction',
    gps_address: 'GA-210-5566',
    visit_date: '2026-09-20',
    service_attended: 'Midweek Miracle Encounter',
    invited_by: 'Brother Benjamin Antwi',
    how_heard: 'Social Media / Facebook Live',
    prayer_request: 'Spiritual deliverance and clarity of purpose for university graduation.',
    follow_up_status: 'converted_to_member',
    assigned_to: 'usr-3',
    assigned_to_name: 'Emmanuel Osei',
    converted_to_member_id: 'mem-9',
    notes: 'Attended Foundation Class on Saturday. Now fully integrated into the Young Adults Fellowship.',
    created_at: '2026-09-20T20:30:00.000Z',
    updated_at: '2026-09-28T16:00:00.000Z',
  },
  {
    id: 'vis-4',
    full_name: 'Mercy Korkor Tetteh',
    gender: 'female',
    phone: '+233 54 990 0112',
    address: 'Anyaa Last Stop',
    gps_address: 'GA-190-7711',
    visit_date: '2026-09-25',
    service_attended: 'Prophetic Hour & All-Night Vigil',
    invited_by: 'Sister Abena Serwaa',
    how_heard: 'Friend / Church Member',
    prayer_request: 'Conception and fruit of the womb after 3 years of marriage.',
    follow_up_status: 'follow_up_required',
    assigned_to: 'usr-2',
    assigned_to_name: 'Clara Gaewornu',
    notes: 'Very touched by the midnight deliverance prayers. Requested pastoral counseling with Prophet Elisha.',
    created_at: '2026-09-26T04:30:00.000Z',
    updated_at: '2026-09-28T09:00:00.000Z',
  },
  {
    id: 'vis-5',
    full_name: 'Caleb Evans Cudjoe',
    gender: 'male',
    phone: '+233 24 555 8800',
    address: 'Joma Top Town',
    gps_address: 'GA-183-9900',
    visit_date: '2026-10-02',
    service_attended: 'Sunday Prophetic Celebration Service',
    how_heard: 'Personal Search / Passed By',
    prayer_request: 'Guidance and financial provision for family building project.',
    follow_up_status: 'new',
    assigned_to: 'usr-5',
    assigned_to_name: 'Kwame Mensah',
    notes: 'First time in Joma area, moved here 2 weeks ago from Kumasi. Warmly welcomed with visitor welcome pack.',
    created_at: '2026-10-02T11:00:00.000Z',
    updated_at: '2026-10-02T11:00:00.000Z',
  },
];

export const sampleHeadcounts: HeadcountRecord[] = [
  {
    id: 'hc-1',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-27',
    men: 68,
    women: 94,
    youth: 42,
    children: 38,
    visitors: 12,
    ushers_protocol: 16,
    online_viewers: 85,
    total_auditorium: 242,
    notes: 'Special Thanksgiving Sunday service. High attendance, additional overflow chairs set up.',
    counted_by: 'Brother Kwame Mensah',
    created_at: '2026-09-27T11:30:00.000Z',
  },
  {
    id: 'hc-2',
    service_id: 'srv-2',
    service_name: 'Midweek Miracle & Breakthrough Encounter',
    date: '2026-09-23',
    men: 34,
    women: 56,
    youth: 28,
    children: 16,
    visitors: 6,
    ushers_protocol: 8,
    online_viewers: 62,
    total_auditorium: 134,
    notes: 'Communion and healing service. Powerful impartation service.',
    counted_by: 'Brother Kwame Mensah',
    created_at: '2026-09-23T20:15:00.000Z',
  },
  {
    id: 'hc-3',
    service_id: 'srv-3',
    service_name: 'Prophetic Hour & All-Night Vigil',
    date: '2026-09-25',
    men: 52,
    women: 78,
    youth: 39,
    children: 12,
    visitors: 15,
    ushers_protocol: 12,
    online_viewers: 110,
    total_auditorium: 181,
    notes: 'Deliverance and night of open heavens. Over 110 concurrent online viewers on Facebook Live.',
    counted_by: 'Brother Kwame Mensah',
    created_at: '2026-09-26T03:45:00.000Z',
  },
  {
    id: 'hc-4',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-20',
    men: 64,
    women: 88,
    youth: 39,
    children: 35,
    visitors: 9,
    ushers_protocol: 14,
    online_viewers: 72,
    total_auditorium: 226,
    notes: 'Sermon on Exceeding Abundantly (Ephesians 3:20). 4 souls gave their lives to Christ.',
    counted_by: 'Brother Kwame Mensah',
    created_at: '2026-09-20T11:30:00.000Z',
  },
];

export const sampleAttendance: AttendanceRecord[] = [
  {
    id: 'att-1',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-27',
    member_id: 'mem-1',
    member_name: 'Kwame Mensah',
    person_name: 'Kwame Mensah',
    person_type: 'member',
    check_in_time: '08:15',
    check_in_method: 'qr_code',
    status: 'present',
    recorded_by: 'System Kiosk',
  },
  {
    id: 'att-2',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-27',
    member_id: 'mem-2',
    member_name: 'Akosua Frimpong',
    person_name: 'Akosua Frimpong',
    person_type: 'member',
    check_in_time: '08:20',
    check_in_method: 'mobile',
    status: 'present',
    recorded_by: 'System Kiosk',
  },
  {
    id: 'att-3',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-27',
    member_id: 'mem-3',
    member_name: 'Kofi Addo',
    person_name: 'Kofi Addo',
    person_type: 'member',
    check_in_time: '08:10',
    check_in_method: 'search',
    status: 'present',
    recorded_by: 'Brother Kwame Mensah',
  },
  {
    id: 'att-4',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-27',
    member_id: 'mem-4',
    member_name: 'Abena Serwaa',
    person_name: 'Abena Serwaa',
    person_type: 'member',
    check_in_time: '08:25',
    check_in_method: 'qr_code',
    status: 'present',
    recorded_by: 'System Kiosk',
  },
  {
    id: 'att-5',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-27',
    member_id: 'mem-5',
    member_name: 'Benjamin Antwi',
    person_name: 'Benjamin Antwi',
    person_type: 'member',
    check_in_time: '07:45',
    check_in_method: 'manual',
    status: 'present',
    recorded_by: 'Brother Kwame Mensah',
  },
  {
    id: 'att-6',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-27',
    member_id: 'mem-6',
    member_name: 'Grace Ansah',
    person_name: 'Grace Ansah',
    person_type: 'member',
    check_in_time: '08:22',
    check_in_method: 'search',
    status: 'present',
    recorded_by: 'Brother Kwame Mensah',
  },
  {
    id: 'att-7',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-27',
    visitor_id: 'vis-1',
    visitor_name: 'Prince Daniel Kwarteng',
    person_name: 'Prince Daniel Kwarteng',
    person_type: 'visitor',
    check_in_time: '08:35',
    check_in_method: 'manual',
    status: 'present',
    recorded_by: 'Brother Kwame Mensah',
  },
  {
    id: 'att-8',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-27',
    visitor_id: 'vis-2',
    visitor_name: 'Rita Serwaa Boateng',
    person_name: 'Rita Serwaa Boateng',
    person_type: 'visitor',
    check_in_time: '08:40',
    check_in_method: 'manual',
    status: 'present',
    recorded_by: 'Brother Kwame Mensah',
  },
];

export const sampleGiving: GivingRecord[] = [
  {
    id: 'giv-1',
    member_id: 'mem-3',
    member_name: 'Kofi Addo',
    tithe_number: 'T-1003',
    donor_name: 'Elder Kofi Addo',
    category: 'Tithe',
    amount: 1200,
    currency: 'GHS',
    date: '2026-09-27',
    payment_method: 'mobile_money',
    payment_channel: 'MTN MoMo',
    reference_number: 'MOMO-72910482',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    notes: 'September Business Tithe',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-27T11:45:00.000Z',
  },
  {
    id: 'giv-2',
    member_id: 'mem-2',
    member_name: 'Akosua Frimpong',
    tithe_number: 'T-1002',
    donor_name: 'Akosua Frimpong',
    category: 'Tithe',
    amount: 850,
    currency: 'GHS',
    date: '2026-09-27',
    payment_method: 'bank_transfer',
    payment_channel: 'Ecobank Ghana',
    reference_number: 'ECO-9921048',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    notes: 'September Monthly Tithe',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-27T11:46:00.000Z',
  },
  {
    id: 'giv-3',
    donor_name: 'Congregational General Collection',
    category: 'Offering',
    amount: 2840,
    currency: 'GHS',
    date: '2026-09-27',
    payment_method: 'cash',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    notes: 'Sunday First & Second General Offering combined count',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-27T12:00:00.000Z',
  },
  {
    id: 'giv-4',
    member_id: 'mem-1',
    member_name: 'Kwame Mensah',
    donor_name: 'Kwame Mensah',
    category: 'Building Fund',
    amount: 500,
    currency: 'GHS',
    date: '2026-09-27',
    payment_method: 'mobile_money',
    payment_channel: 'Telecel Cash',
    reference_number: 'TEL-8831092',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    notes: 'Cathedral Sanctuary Expansion contribution',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-27T11:50:00.000Z',
  },
  {
    id: 'giv-5',
    member_id: 'mem-4',
    member_name: 'Abena Serwaa',
    tithe_number: 'T-1004',
    donor_name: 'Abena Serwaa',
    category: 'Tithe',
    amount: 600,
    currency: 'GHS',
    date: '2026-09-27',
    payment_method: 'mobile_money',
    payment_channel: 'MTN MoMo',
    reference_number: 'MOMO-3391820',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    notes: 'Faithful Tithe',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-27T11:52:00.000Z',
  },
  {
    id: 'giv-6',
    member_id: 'mem-5',
    member_name: 'Benjamin Antwi',
    donor_name: 'Benjamin Antwi',
    category: 'Seed',
    amount: 750,
    currency: 'GHS',
    date: '2026-09-25',
    payment_method: 'mobile_money',
    payment_channel: 'MTN MoMo',
    reference_number: 'MOMO-4401928',
    service_id: 'srv-3',
    service_name: 'Prophetic Hour & All-Night Vigil',
    notes: 'All-Night Prophetic Altar Seed for project victory',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-26T02:00:00.000Z',
  },
  {
    id: 'giv-7',
    member_id: 'mem-7',
    member_name: 'Samuel Tetteh',
    donor_name: 'Samuel Tetteh',
    category: 'Thanksgiving',
    amount: 1500,
    currency: 'GHS',
    date: '2026-09-20',
    payment_method: 'cash',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    notes: 'Special Thanksgiving for new delivery van purchase',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-20T11:40:00.000Z',
  },
];

export const sampleCampaigns: PledgeCampaign[] = [
  {
    id: 'camp-1',
    name: 'Cathedral Sanctuary Expansion 2026',
    target_amount: 250000,
    start_date: '2026-01-01',
    end_date: '2026-12-31',
    description: 'Procurement of structural steel framing, auditorium roofing, and acoustic insulation for the main auditorium expansion.',
    is_active: true,
  },
  {
    id: 'camp-2',
    name: 'Media & Sound Modernization Project',
    target_amount: 60000,
    start_date: '2026-05-01',
    end_date: '2026-11-30',
    description: 'Digital 32-channel sound console, wireless vocal microphones, 4K broadcast cameras, and streaming encoders.',
    is_active: true,
  },
];

export const samplePledges: PledgeRecord[] = [
  {
    id: 'pld-1',
    campaign_id: 'camp-1',
    campaign_name: 'Cathedral Sanctuary Expansion 2026',
    member_id: 'mem-3',
    member_name: 'Kofi Addo',
    member_phone: '+233 24 111 2233',
    amount_pledged: 15000,
    amount_paid: 10000,
    balance: 5000,
    start_date: '2026-02-01',
    due_date: '2026-11-30',
    status: 'partially_paid',
    notes: 'GH₵ 5,000 paid via MoMo in April, GH₵ 5,000 paid in August.',
    created_at: '2026-02-01T10:00:00.000Z',
    updated_at: '2026-08-15T10:00:00.000Z',
  },
  {
    id: 'pld-2',
    campaign_id: 'camp-1',
    campaign_name: 'Cathedral Sanctuary Expansion 2026',
    member_id: 'mem-2',
    member_name: 'Akosua Frimpong',
    member_phone: '+233 27 555 4321',
    amount_pledged: 8000,
    amount_paid: 8000,
    balance: 0,
    start_date: '2026-02-15',
    due_date: '2026-09-30',
    status: 'completed',
    notes: 'Pledge fully honored! Official receipt issued.',
    created_at: '2026-02-15T10:00:00.000Z',
    updated_at: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'pld-3',
    campaign_id: 'camp-2',
    campaign_name: 'Media & Sound Modernization Project',
    member_id: 'mem-5',
    member_name: 'Benjamin Antwi',
    member_phone: '+233 24 777 6655',
    amount_pledged: 5000,
    amount_paid: 3500,
    balance: 1500,
    start_date: '2026-05-10',
    due_date: '2026-10-31',
    status: 'partially_paid',
    notes: 'Media team leader pledge towards digital console.',
    created_at: '2026-05-10T10:00:00.000Z',
    updated_at: '2026-09-12T10:00:00.000Z',
  },
  {
    id: 'pld-4',
    campaign_id: 'camp-1',
    campaign_name: 'Cathedral Sanctuary Expansion 2026',
    member_id: 'mem-1',
    member_name: 'Kwame Mensah',
    member_phone: '+233 24 333 8899',
    amount_pledged: 4000,
    amount_paid: 2000,
    balance: 2000,
    start_date: '2026-03-01',
    due_date: '2026-12-15',
    status: 'partially_paid',
    notes: 'Monthly installments of GH₵ 500.',
    created_at: '2026-03-01T10:00:00.000Z',
    updated_at: '2026-09-27T12:00:00.000Z',
  },
  {
    id: 'pld-5',
    campaign_id: 'camp-2',
    campaign_name: 'Media & Sound Modernization Project',
    member_id: 'mem-9',
    member_name: 'David Quaye',
    member_phone: '+233 54 888 3322',
    amount_pledged: 2500,
    amount_paid: 2500,
    balance: 0,
    start_date: '2026-06-01',
    due_date: '2026-09-15',
    status: 'completed',
    notes: 'Fully redeemed in two installments.',
    created_at: '2026-06-01T10:00:00.000Z',
    updated_at: '2026-09-15T10:00:00.000Z',
  },
];

export const sampleExpenses: ExpenseRecord[] = [
  {
    id: 'exp-1',
    category: 'Utilities & Power',
    title: 'Electricity Company of Ghana (ECG) Bill',
    recipient: 'ECG Prepayment Depot, Ablekuma',
    amount: 1450,
    currency: 'GHS',
    date: '2026-09-24',
    account: 'Operations Account',
    payment_method: 'mobile_money',
    reference_number: 'ECG-771920',
    description: 'Prepaid power credit replenishment for main sanctuary air conditioning and floodlights.',
    approved_by: 'Prophet Elisha K. Richard',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-24T14:00:00.000Z',
  },
  {
    id: 'exp-2',
    category: 'Maintenance & Facility',
    title: 'Diesel Generator Fuel & Oil Service',
    recipient: 'TotalEnergies Ablekuma Highway',
    amount: 1200,
    currency: 'GHS',
    date: '2026-09-22',
    account: 'Operations Account',
    payment_method: 'cash',
    description: '100 Litres diesel fuel purchase and synthetic engine oil filter change for standby 65kVA generator.',
    approved_by: 'Elder Kofi Addo',
    recorded_by: 'Brother Kwame Mensah',
    created_at: '2026-09-22T10:30:00.000Z',
  },
  {
    id: 'exp-3',
    category: 'Welfare & Charity',
    title: 'Widows & Vulnerable Families Food Support',
    recipient: 'GWCC Welfare Committee',
    amount: 1800,
    currency: 'GHS',
    date: '2026-09-18',
    account: 'Welfare Account',
    payment_method: 'mobile_money',
    reference_number: 'WEL-551902',
    description: 'Monthly welfare packages (rice bags, cooking oil, canned fish) for 12 elderly widows and single mothers in Joma community.',
    approved_by: 'Prophet Elisha K. Richard',
    recorded_by: 'Brother Samuel Tetteh',
    created_at: '2026-09-18T16:00:00.000Z',
  },
  {
    id: 'exp-4',
    category: 'Media & Technology',
    title: 'High-Speed Fiber Internet Subscription',
    recipient: 'Telecel Ghana Broadband',
    amount: 650,
    currency: 'GHS',
    date: '2026-09-05',
    account: 'Operations Account',
    payment_method: 'bank_transfer',
    reference_number: 'TEL-441098',
    description: 'Monthly unlimited church dedicated fiber internet for Sunday and midweek online livestreaming.',
    approved_by: 'Prophet Elisha K. Richard',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-05T09:00:00.000Z',
  },
];

export const sampleEvents: ChurchEvent[] = [
  {
    id: 'evt-1',
    title: 'Annual Greater Works Prophetic Convention 2026',
    description: 'Three nights and one grand Sunday of supernatural encounters, prophetic insight, and financial unction.',
    theme: 'Exceeding Abundantly (Ephesians 3:20)',
    theme_scripture: 'Ephesians 3:20',
    event_type: 'conference',
    start_date: '2026-10-21',
    end_date: '2026-10-25',
    start_time: '18:00',
    end_time: '21:30',
    venue: 'City of Refuge Main Sanctuary, Joma',
    organizer: 'General Church Council',
    speaker: 'Prophet Elisha K. Richard & Guest Apostles',
    expected_attendance: 450,
    budget: 35000,
    status: 'upcoming',
    requires_registration: true,
    registration_count: 85,
    banner_color: '#065f46',
    created_at: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'evt-2',
    title: 'Community Free Health Screening & Gospel Crusade',
    description: 'Free blood pressure checks, diabetes screening, doctor consultations, and open-air gospel proclamation in Joma market square.',
    theme: 'Healing for the Nations',
    event_type: 'community_outreach',
    start_date: '2026-10-10',
    end_date: '2026-10-10',
    start_time: '08:00',
    end_time: '15:00',
    venue: 'Joma Community Market Square',
    organizer: 'Evangelism & Welfare Ministry',
    speaker: 'Pastor Emmanuel Osei',
    expected_attendance: 300,
    budget: 8500,
    status: 'upcoming',
    requires_registration: false,
    banner_color: '#0284c7',
    created_at: '2026-09-10T10:00:00.000Z',
  },
  {
    id: 'evt-3',
    title: 'Night of Open Heavens & Prophetic Deliverance',
    description: 'All-night spiritual warfare, prophetic breakings of ancestral yokes, and divine empowerment.',
    theme: 'Loose Him and Let Him Go',
    event_type: 'all_night',
    start_date: '2026-10-30',
    end_date: '2026-10-31',
    start_time: '22:00',
    end_time: '04:30',
    venue: 'City of Refuge Main Sanctuary, Joma',
    organizer: 'Pastoral Council',
    speaker: 'Prophet Elisha K. Richard',
    expected_attendance: 250,
    budget: 4500,
    status: 'upcoming',
    requires_registration: false,
    banner_color: '#4f46e5',
    created_at: '2026-09-15T10:00:00.000Z',
  },
];

export const samplePastoralCare: PastoralCareRecord[] = [
  {
    id: 'pc-1',
    member_id: 'mem-1',
    member_name: 'Kwame Mensah',
    member_phone: '+233 24 333 8899',
    date: '2026-09-22',
    care_type: 'home_visit',
    pastor_name: 'Prophet Elisha K. Richard',
    assigned_pastor: 'Prophet Elisha K. Richard',
    notes: 'Pastoral home visitation and family prayer dedication for the Mensah household. Dedicated their new home addition to God in prayer.',
    action_items: 'Follow up in two weeks regarding family cell attendance.',
    status: 'completed',
    is_confidential: false,
    created_at: '2026-09-22T17:00:00.000Z',
  },
  {
    id: 'pc-2',
    member_id: 'mem-4',
    member_name: 'Abena Serwaa',
    member_phone: '+233 20 333 4455',
    date: '2026-09-15',
    care_type: 'counseling',
    pastor_name: 'Pastor Emmanuel Osei',
    assigned_pastor: 'Pastor Emmanuel Osei',
    notes: 'Career and ministry balance counseling. Encouraged her to continue leading the youth fellowship with joy and structured delegation.',
    status: 'completed',
    is_confidential: true,
    created_at: '2026-09-15T15:30:00.000Z',
  },
  {
    id: 'pc-3',
    member_id: 'mem-6',
    member_name: 'Grace Ansah',
    member_phone: '+233 50 123 9876',
    date: '2026-09-28',
    care_type: 'new_birth',
    pastor_name: 'Pastor Emmanuel Osei',
    assigned_pastor: 'Pastor Emmanuel Osei',
    notes: 'Baby dedication counseling for sister Grace Ansah and husband Michael Ansah. Preparation for dedication service in November.',
    action_items: 'Schedule baby dedication on the first Sunday of November 2026.',
    status: 'in_progress',
    is_confidential: false,
    created_at: '2026-09-28T16:00:00.000Z',
  },
];

export const samplePrayerRequests: PrayerRequest[] = [
  {
    id: 'pr-1',
    member_id: 'mem-7',
    requester_name: 'Samuel Tetteh',
    requester_phone: '+233 24 999 1122',
    category: 'Business & Finance',
    request: 'Pray for favorable terms on long-term agricultural wholesale supply contract with supermarket chains in Accra.',
    date_submitted: '2026-09-26',
    assigned_leader: 'Prophet Elisha K. Richard',
    status: 'praying',
    is_confidential: false,
    created_at: '2026-09-26T08:00:00.000Z',
  },
  {
    id: 'pr-2',
    member_id: 'mem-8',
    requester_name: 'Faustina Mensah',
    requester_phone: '+233 20 444 7711',
    category: 'Healing & Health',
    request: 'Thanksgiving to God! Mother who was hospitalized with respiratory distress has been discharged safely.',
    date_submitted: '2026-09-20',
    assigned_leader: 'Pastor Emmanuel Osei',
    status: 'answered',
    testimony: 'Doctors confirmed complete recovery without needing surgical intervention. God has shown Himself faithful!',
    is_confidential: false,
    created_at: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'pr-3',
    requester_name: 'Prince Daniel Kwarteng',
    requester_phone: '+233 55 123 7890',
    category: 'Job & Employment',
    request: 'Praying for success in upcoming job assessment with the Maritime Authority. Trusting God for divine favor.',
    date_submitted: '2026-09-27',
    assigned_leader: 'Brother Kwame Mensah',
    status: 'praying',
    is_confidential: false,
    created_at: '2026-09-27T12:00:00.000Z',
  },
];

export const sampleCommunications: CommunicationRecord[] = [
  {
    id: 'com-1',
    title: 'Sunday Prophetic Celebration Reminder',
    channel: 'sms',
    recipient_type: 'all_members',
    recipient_count: 142,
    message: 'Shalom Beloved of Greater Works City Church! Join us tomorrow Sunday at 8:30 AM for a glorious Prophetic Celebration Service. Your miracle awaits you. Ephesians 3:20.',
    sender_id: 'usr-2',
    status: 'sent',
    sent_at: '2026-09-26T18:00:00.000Z',
    created_by: 'Clara Gaewornu',
  },
  {
    id: 'com-2',
    title: 'Midweek Miracle Encounter Broadcast',
    channel: 'whatsapp',
    recipient_type: 'all_members',
    recipient_count: 156,
    message: 'Greetings in Christ! It is Wednesday Miracle Encounter at 6:30 PM. Come fasting and expecting divine intervention in every stubborn battle. Main Sanctuary, Joma.',
    sender_id: 'usr-2',
    status: 'sent',
    sent_at: '2026-09-23T14:00:00.000Z',
    created_by: 'Clara Gaewornu',
  },
];

export const sampleAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    user_name: 'Prophet Elisha K. Richard',
    user_role: 'senior_pastor',
    action: 'SYSTEM_INITIALIZATION',
    module: 'System',
    details: 'GWCC ChMS instance initialized with full church configuration and ministerial data.',
    timestamp: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'log-2',
    user_name: 'Deaconess Akosua Frimpong',
    user_role: 'finance_officer',
    action: 'RECORD_GIVING',
    module: 'Finance',
    record_id: 'giv-1',
    details: 'Recorded Tithe of GH₵ 1,200.00 from Elder Kofi Addo via MTN MoMo.',
    timestamp: '2026-09-27T11:45:00.000Z',
  },
  {
    id: 'log-3',
    user_name: 'Brother Kwame Mensah',
    user_role: 'attendance_officer',
    action: 'RECORD_HEADCOUNT',
    module: 'Attendance',
    record_id: 'hc-1',
    details: 'Submitted Sunday service headcount: 242 total auditorium attendees.',
    timestamp: '2026-09-27T11:30:00.000Z',
  },
];

// ==========================================
// SAMPLE WELFARE CONTRIBUTIONS (MONTHLY DUES)
// ==========================================
export const sampleWelfareContributions: WelfareContribution[] = [
  {
    id: 'wlf-c1',
    member_id: 'mem-1',
    member_name: 'Kwame Mensah',
    tithe_number: 'T-1001',
    date: '2026-09-06',
    month: '2026-09',
    amount: 50.0,
    payment_method: 'mobile_money',
    payment_channel: 'MTN Mobile Money',
    reference_no: 'WLF-2609-001',
    notes: 'September welfare dues paid via MoMo',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-06T10:15:00.000Z',
  },
  {
    id: 'wlf-c2',
    member_id: 'mem-2',
    member_name: 'Abena Serwaa',
    tithe_number: 'T-1002',
    date: '2026-09-06',
    month: '2026-09',
    amount: 50.0,
    payment_method: 'cash',
    payment_channel: 'Cash Desk',
    reference_no: 'WLF-2609-002',
    notes: 'Paid at welfare counter after 1st service',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-06T11:00:00.000Z',
  },
  {
    id: 'wlf-c3',
    member_id: 'mem-3',
    member_name: 'Kofi Addo',
    tithe_number: 'T-1003',
    date: '2026-09-13',
    month: '2026-09',
    amount: 100.0,
    payment_method: 'mobile_money',
    payment_channel: 'Telecel Cash',
    reference_no: 'WLF-2609-003',
    notes: 'Elder Kofi Addo monthly welfare + voluntary benevolence gift',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-13T09:40:00.000Z',
  },
  {
    id: 'wlf-c4',
    member_id: 'mem-4',
    member_name: 'Mercy Appiah',
    tithe_number: 'T-1004',
    date: '2026-08-30',
    month: '2026-08',
    amount: 50.0,
    payment_method: 'cash',
    payment_channel: 'Cash Desk',
    reference_no: 'WLF-2608-019',
    notes: 'August welfare dues',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-08-30T10:20:00.000Z',
  },
  {
    id: 'wlf-c5',
    member_id: 'mem-5',
    member_name: 'Benjamin Antwi',
    tithe_number: 'T-1005',
    date: '2026-09-20',
    month: '2026-09',
    amount: 50.0,
    payment_method: 'mobile_money',
    payment_channel: 'MTN Mobile Money',
    reference_no: 'WLF-2609-012',
    notes: 'September dues confirmation received',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-20T12:05:00.000Z',
  },
  {
    id: 'wlf-c6',
    member_id: 'mem-1',
    member_name: 'Kwame Mensah',
    tithe_number: 'T-1001',
    date: '2026-08-02',
    month: '2026-08',
    amount: 50.0,
    payment_method: 'mobile_money',
    payment_channel: 'MTN Mobile Money',
    reference_no: 'WLF-2608-002',
    notes: 'August welfare dues',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-08-02T09:30:00.000Z',
  },
];

// ==========================================
// SAMPLE WELFARE CLAIMS & AID APPLICATIONS
// ==========================================
export const sampleWelfareClaims: WelfareClaim[] = [
  {
    id: 'claim-1',
    claim_number: 'BEN-2026-001',
    member_id: 'mem-4',
    member_name: 'Mercy Appiah',
    member_phone: '+233 24 555 1212',
    category: 'childbirth_naming',
    title: 'Maternity Benevolence & Baby Naming Blessing',
    description: 'Sister Mercy delivered a healthy baby girl at Ga South Municipal Hospital. Welfare committee maternity grant for baby essentials and outdoor ceremony.',
    amount_requested: 600.0,
    amount_approved: 600.0,
    status: 'disbursed',
    emergency_level: 'normal',
    date_submitted: '2026-09-02',
    date_reviewed: '2026-09-04',
    reviewed_by: 'Prophet Elisha K. Richard & Welfare Board',
    pastoral_notes: 'Approved fully as per GWCC welfare policy Article 4. Pastor Emmanuel Osei officiated the hospital dedication.',
    disbursement_date: '2026-09-05',
    disbursement_method: 'mobile_money',
    disbursement_channel: 'MTN Mobile Money',
    disbursement_voucher_no: 'WPV-2026-084',
    supporting_documents: 'Ga South Hospital birth notification slip',
    created_at: '2026-09-02T14:30:00.000Z',
  },
  {
    id: 'claim-2',
    claim_number: 'BEN-2026-002',
    member_id: 'mem-5',
    member_name: 'Benjamin Antwi',
    member_phone: '+233 24 777 6655',
    category: 'hospital_medical',
    title: 'Emergency Medical & Surgery Support',
    description: 'Brother Benjamin underwent emergency surgery at Korle Bu Teaching Hospital after a sudden appendicitis complication. Requesting welfare medical relief.',
    amount_requested: 1500.0,
    amount_approved: 1200.0,
    status: 'disbursed',
    emergency_level: 'critical',
    date_submitted: '2026-09-12',
    date_reviewed: '2026-09-13',
    reviewed_by: 'Prophet Elisha K. Richard',
    pastoral_notes: 'Critical intervention authorized immediately. Elder Kofi Addo and Welfare Chair visited in ward.',
    disbursement_date: '2026-09-14',
    disbursement_method: 'mobile_money',
    disbursement_channel: 'MTN MoMo (Hospital Pharmacy Desk)',
    disbursement_voucher_no: 'WPV-2026-091',
    supporting_documents: 'Korle Bu Surgical admission letter & pharmacy bill invoice',
    created_at: '2026-09-12T08:15:00.000Z',
  },
  {
    id: 'claim-3',
    claim_number: 'BEN-2026-003',
    member_id: 'mem-2',
    member_name: 'Abena Serwaa',
    member_phone: '+233 20 333 4455',
    category: 'bereavement',
    title: 'Bereavement Assistance - Loss of Father',
    description: 'Sister Abena Serwaa lost her biological father (Late Opanyin Kwadwo Boakye) at Mampong Ashanti. Requesting bereavement support for funeral logistics.',
    amount_requested: 2000.0,
    amount_approved: 2000.0,
    status: 'approved',
    emergency_level: 'urgent',
    date_submitted: '2026-09-22',
    date_reviewed: '2026-09-24',
    reviewed_by: 'Welfare Committee & Clara Gaewornu',
    pastoral_notes: 'Approved standard Category A Bereavement Benefit. Church delegation led by Pastor Emmanuel Osei scheduled to attend funeral rites.',
    disbursement_voucher_no: 'WPV-2026-099',
    supporting_documents: 'Official obituary announcement & mortuary receipt',
    created_at: '2026-09-22T11:00:00.000Z',
  },
  {
    id: 'claim-4',
    claim_number: 'BEN-2026-004',
    member_id: 'mem-1',
    member_name: 'Kwame Mensah',
    member_phone: '+233 24 333 8899',
    category: 'education_welfare',
    title: 'Secondary School Education Subsidy Assistance',
    description: 'Support for brother Kwame Mensah elder son secondary school boarding supplies and tuition deficit at Presbyterian Boys Senior High.',
    amount_requested: 800.0,
    status: 'pending',
    emergency_level: 'normal',
    date_submitted: '2026-09-28',
    pastoral_notes: 'Submitted for upcoming Welfare Board meeting on Thursday.',
    supporting_documents: 'School term admission prospectus & fee schedule',
    created_at: '2026-09-28T16:20:00.000Z',
  },
];

// ==========================================
// SAMPLE CHILDREN'S MINISTRY SAFETY CHECK-INS
// ==========================================
export const sampleChildCheckIns: ChildCheckInRecord[] = [
  {
    id: 'chk-child-1',
    security_code: 'GWCC-K412',
    child_name: 'Samuel Mensah',
    age_group: 'beginners',
    class_room: 'Samuel Hall (Ages 4-6)',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration & Miracle Encounter',
    date: '2026-09-27',
    check_in_time: '08:42 AM',
    parent_name: 'Kwame Mensah',
    parent_phone: '+233 24 333 8899',
    parent_member_id: 'mem-1',
    alternate_pickup_name: 'Grace Mensah (Auntie)',
    alternate_pickup_phone: '+233 20 111 9988',
    allergies_medical_notes: 'Mild asthma; inhaler in front pouch of yellow school bag',
    has_allergy_alert: true,
    special_instructions: 'Please ensure he takes water during mid-service break',
    status: 'checked_in',
    checked_in_by: 'Sister Evelyn Boateng (Children Teacher)',
    created_at: '2026-09-27T08:42:00.000Z',
  },
  {
    id: 'chk-child-2',
    security_code: 'GWCC-K415',
    child_name: 'Eunice Addo',
    age_group: 'juniors',
    class_room: 'David Hall (Ages 7-9)',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration & Miracle Encounter',
    date: '2026-09-27',
    check_in_time: '08:50 AM',
    parent_name: 'Elder Kofi Addo',
    parent_phone: '+233 24 111 2233',
    parent_member_id: 'mem-3',
    alternate_pickup_name: 'Mrs. Patience Addo',
    alternate_pickup_phone: '+233 24 111 2234',
    allergies_medical_notes: 'None reported',
    has_allergy_alert: false,
    special_instructions: 'Likes sitting in front row with children choir',
    status: 'checked_in',
    checked_in_by: 'Sister Evelyn Boateng',
    created_at: '2026-09-27T08:50:00.000Z',
  },
  {
    id: 'chk-child-3',
    security_code: 'GWCC-K418',
    child_name: 'Prince Antwi',
    age_group: 'nursery_toddler',
    class_room: 'Hannah Hall (Nursery & Toddlers 1-3)',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration & Miracle Encounter',
    date: '2026-09-27',
    check_in_time: '08:58 AM',
    parent_name: 'Benjamin Antwi',
    parent_phone: '+233 24 777 6655',
    parent_member_id: 'mem-5',
    allergies_medical_notes: 'Lactose intolerant - do not give dairy biscuits',
    has_allergy_alert: true,
    special_instructions: 'Extra bottle of boiled water and soft wipes provided in baby diaper bag',
    status: 'checked_in',
    checked_in_by: 'Deaconess Mercy Darko',
    created_at: '2026-09-27T08:58:00.000Z',
  },
  {
    id: 'chk-child-4',
    security_code: 'GWCC-K399',
    child_name: 'Priscilla Osei',
    age_group: 'pre_teens',
    class_room: 'Timothy Hall (Pre-Teens 10-12)',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration & Miracle Encounter',
    date: '2026-09-27',
    check_in_time: '08:35 AM',
    parent_name: 'Pastor Emmanuel Osei',
    parent_phone: '+233 24 987 6543',
    allergies_medical_notes: 'None',
    has_allergy_alert: false,
    status: 'checked_out',
    checked_in_by: 'Sister Evelyn Boateng',
    check_out_time: '12:15 PM',
    checked_out_to_person: 'Pastor Emmanuel Osei',
    verified_by_leader: 'Sister Evelyn Boateng',
    created_at: '2026-09-27T08:35:00.000Z',
  },
];

// ==========================================
// SAMPLE CHURCH ASSETS & EQUIPMENT REGISTRY
// ==========================================
export const sampleChurchAssets: ChurchAsset[] = [
  {
    id: 'ast-1',
    asset_tag: 'AST-001',
    name: 'Yamaha Motif XF8 88-Key Synthesizer',
    category: 'musical_instruments',
    department: 'Voice of Grace (Music/Choir)',
    brand: 'Yamaha',
    model: 'Motif XF8',
    serial_number: 'YMH-XF8-2024-819',
    purchase_date: '2024-03-15',
    purchase_cost: 38500.0,
    current_condition: 'working',
    location: 'Main Sanctuary Altar Stage (Left)',
    custodian_name: 'Pastor Emmanuel Osei',
    last_service_date: '2026-08-10',
    next_service_date: '2026-11-15',
    notes: 'Main worship keyboard; key contacts cleaned and calibrated by Music Tech Accra.',
    maintenance_logs: [
      {
        id: 'mlog-1',
        asset_id: 'ast-1',
        service_date: '2026-08-10',
        service_type: 'routine_maintenance',
        technician_vendor: 'Acoustic Labs Ghana, Osu',
        cost: 650.0,
        details: 'Key contact strip replacement and internal dust vacuuming.',
        performed_by: 'Pastor Emmanuel Osei',
      },
    ],
    created_at: '2024-03-15T09:00:00.000Z',
  },
  {
    id: 'ast-2',
    asset_tag: 'AST-002',
    name: 'Behringer X32 40-Channel Digital Mixer',
    category: 'audio_sound',
    department: 'Sound & Audio Engineering',
    brand: 'Behringer',
    model: 'X32 Digital',
    serial_number: 'BH-X32-901824',
    purchase_date: '2023-11-20',
    purchase_cost: 29500.0,
    current_condition: 'working',
    location: 'Main Sanctuary Sound Control Booth',
    custodian_name: 'Brother Kwame Mensah',
    last_service_date: '2026-07-05',
    next_service_date: '2027-01-10',
    notes: 'Firmware updated to v4.08. Motorized faders calibrated.',
    maintenance_logs: [
      {
        id: 'mlog-2',
        asset_id: 'ast-2',
        service_date: '2026-07-05',
        service_type: 'routine_maintenance',
        technician_vendor: 'SoundPro West Africa, Circle',
        cost: 850.0,
        details: 'Motorized fader alignment and digital snake AES50 port inspection.',
        performed_by: 'Brother Kwame Mensah',
      },
    ],
    created_at: '2023-11-20T10:30:00.000Z',
  },
  {
    id: 'ast-3',
    asset_tag: 'AST-003',
    name: 'Perkins 60kVA Silent Standby Diesel Generator',
    category: 'power_facility',
    department: 'Facility & Logistics',
    brand: 'Perkins / FG Wilson',
    model: 'P60-4S',
    serial_number: 'PRK-60KVA-GH-1092',
    purchase_date: '2023-06-10',
    purchase_cost: 88000.0,
    current_condition: 'working',
    location: 'Generator Shed (Church Compound Rear)',
    custodian_name: 'Elder Kofi Addo',
    last_service_date: '2026-09-01',
    next_service_date: '2026-12-01',
    notes: 'Automatic Transfer Switch (ATS) functional. Full diesel filter change completed in September.',
    maintenance_logs: [
      {
        id: 'mlog-3',
        asset_id: 'ast-3',
        service_date: '2026-09-01',
        service_type: 'routine_maintenance',
        technician_vendor: 'Mantrac Ghana Field Engineers',
        cost: 2400.0,
        details: 'Oil filter, fuel separator, air filter replacement, 50L Total 15W40 lubricant flush.',
        performed_by: 'Elder Kofi Addo',
      },
    ],
    created_at: '2023-06-10T12:00:00.000Z',
  },
  {
    id: 'ast-4',
    asset_tag: 'AST-004',
    name: 'Pearl Masters Maple 6-Piece Professional Drum Kit',
    category: 'musical_instruments',
    department: 'Voice of Grace (Music/Choir)',
    brand: 'Pearl',
    model: 'Masters Maple Complete',
    serial_number: 'PRL-MMC-48192',
    purchase_date: '2024-01-20',
    purchase_cost: 24500.0,
    current_condition: 'working',
    location: 'Main Sanctuary Altar Stage (Right)',
    custodian_name: 'Pastor Emmanuel Osei',
    last_service_date: '2026-08-15',
    notes: 'Includes Zildjian K Custom cymbals set. Bass drum head tuned.',
    created_at: '2024-01-20T14:00:00.000Z',
  },
  {
    id: 'ast-5',
    asset_tag: 'AST-005',
    name: 'Shure SLX-D Dual Wireless Microphone System',
    category: 'audio_sound',
    department: 'Sound & Audio Engineering',
    brand: 'Shure',
    model: 'SLXD4D / Beta58A',
    serial_number: 'SHR-SLXD-7712',
    purchase_date: '2024-05-18',
    purchase_cost: 16800.0,
    current_condition: 'working',
    location: 'Pulpit & Stage Altar',
    custodian_name: 'Brother Kwame Mensah',
    notes: 'Dedicated lead wireless mics for Prophet Elisha K. Richard and worship leader.',
    created_at: '2024-05-18T10:00:00.000Z',
  },
  {
    id: 'ast-6',
    asset_tag: 'AST-006',
    name: 'Sony 4K PTZ Remote Live Broadcast Camera',
    category: 'multimedia_broadcast',
    department: 'Media & Communications',
    brand: 'Sony',
    model: 'BRC-X400 4K',
    serial_number: 'SNY-PTZ-9921',
    purchase_date: '2024-09-02',
    purchase_cost: 21500.0,
    current_condition: 'working',
    location: 'Sanctuary Balcony Mount Center',
    custodian_name: 'Sister Clara Gaewornu',
    notes: 'NDI IP protocol livestream controller mounted for Facebook & YouTube live broadcasts.',
    created_at: '2024-09-02T11:00:00.000Z',
  },
  {
    id: 'ast-7',
    asset_tag: 'AST-007',
    name: 'Carrier 3.0HP Floor Standing Inverter Air Conditioner',
    category: 'power_facility',
    department: 'Facility & Logistics',
    brand: 'Carrier',
    model: 'QHG036-Inverter',
    serial_number: 'CRR-3HP-2023-41',
    purchase_date: '2023-08-15',
    purchase_cost: 18200.0,
    current_condition: 'under_maintenance',
    location: 'Main Sanctuary Front Right Wing',
    custodian_name: 'Elder Kofi Addo',
    last_service_date: '2026-09-20',
    notes: 'Compressor gas leak detected; AC technician scheduled for copper coil brazing.',
    maintenance_logs: [
      {
        id: 'mlog-4',
        asset_id: 'ast-7',
        service_date: '2026-09-20',
        service_type: 'repair',
        technician_vendor: 'CoolTech Services, Ablekuma',
        cost: 450.0,
        details: 'Diagnostic inspection for refrigerant pressure drop.',
        performed_by: 'Elder Kofi Addo',
      },
    ],
    created_at: '2023-08-15T09:30:00.000Z',
  },
  {
    id: 'ast-8',
    asset_tag: 'AST-008',
    name: 'Royal Communion Stainless Steel Trays & 500 Cups Set',
    category: 'communion_liturgical',
    department: 'Pastoral Council & Deacons',
    brand: 'Artistic Churchware',
    model: 'Classic 500-Cup Tray Set',
    purchase_date: '2023-02-10',
    purchase_cost: 6500.0,
    current_condition: 'working',
    location: 'Church Vestry / Sacristy Cabinet',
    custodian_name: 'Deaconess Akosua Frimpong',
    notes: 'Used during monthly 1st Sunday Holy Communion services.',
    created_at: '2023-02-10T08:00:00.000Z',
  },
];

export const sampleAssets = sampleChurchAssets;

// ==========================================
// SAMPLE MULTI-DEPARTMENT DUTY ROSTER
// ==========================================
export const sampleRosterAssignments: RosterAssignment[] = [
  {
    id: 'rst-1',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration & Miracle Encounter',
    date: '2026-10-11',
    member_id: 'mem-1',
    member_name: 'Kwame Mensah',
    member_phone: '+233 24 333 8899',
    department: 'sound_media',
    role_title: 'Lead FOH Sound Engineer',
    report_time: '07:30 AM',
    status: 'confirmed',
    notes: 'Setup pulpit microphones and wireless receiver frequency check',
    created_at: '2026-09-28T10:00:00.000Z',
  },
  {
    id: 'rst-2',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration & Miracle Encounter',
    date: '2026-10-11',
    member_id: 'mem-1',
    member_name: 'Kwame Mensah',
    member_phone: '+233 24 333 8899',
    department: 'ushers_protocol',
    role_title: 'Main Entrance Head Usher',
    report_time: '08:00 AM',
    status: 'confirmed',
    notes: 'Assigned to ushering lobby — triggers double-booking alert with Sound Desk!',
    created_at: '2026-09-28T10:05:00.000Z',
  },
  {
    id: 'rst-3',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration & Miracle Encounter',
    date: '2026-10-11',
    member_id: 'mem-2',
    member_name: 'Abena Serwaa',
    member_phone: '+233 20 333 4455',
    department: 'praise_team',
    role_title: 'Worship Leader & Lead Soprano',
    report_time: '07:45 AM',
    status: 'confirmed',
    notes: 'Coordinate worship set with keyboardist and band',
    created_at: '2026-09-28T10:10:00.000Z',
  },
  {
    id: 'rst-4',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration & Miracle Encounter',
    date: '2026-10-11',
    member_id: 'mem-3',
    member_name: 'Kofi Addo',
    member_phone: '+233 24 111 2233',
    department: 'intercessors',
    role_title: 'Pre-Service Altar Intercession Lead',
    report_time: '07:30 AM',
    status: 'confirmed',
    notes: 'Lead 45 minutes prayer before congregational arrival',
    created_at: '2026-09-28T10:15:00.000Z',
  },
  {
    id: 'rst-5',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration & Miracle Encounter',
    date: '2026-10-11',
    member_id: 'mem-4',
    member_name: 'Mercy Appiah',
    member_phone: '+233 24 555 1212',
    department: 'children_ministry',
    role_title: 'Samuel Hall (Beginners 4-6) Teacher',
    report_time: '08:00 AM',
    status: 'confirmed',
    notes: 'Prepare lesson materials for David and Goliath flannelgraph story',
    created_at: '2026-09-28T10:20:00.000Z',
  },
  {
    id: 'rst-6',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration & Miracle Encounter',
    date: '2026-10-11',
    member_id: 'mem-5',
    member_name: 'Benjamin Antwi',
    member_phone: '+233 24 777 6655',
    department: 'sound_media',
    role_title: 'Livestream & Camera Operator',
    report_time: '07:45 AM',
    status: 'confirmed',
    notes: 'Operate PTZ camera controller and monitor YouTube/Facebook audio stream',
    created_at: '2026-09-28T10:25:00.000Z',
  },
];

// ==========================================
// SAMPLE FOUNDATION SCHOOL & DISCIPLESHIP COHORTS
// ==========================================
export const sampleFoundationCohorts: FoundationCohort[] = [
  {
    id: 'fnd-cohort-2026-b',
    name: 'Class of Faith & Power (Cohort 2026-B)',
    start_date: '2026-09-06',
    target_graduation_date: '2026-10-25',
    instructor_name: 'Pastor Emmanuel Osei & Ministerial Council',
    status: 'active',
    notes: '7-week discipleship cohort covering all 5 foundational pillars and holy baptism preparation.',
    created_at: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'fnd-cohort-2026-a',
    name: 'Pioneers of Grace (Cohort 2026-A)',
    start_date: '2026-05-03',
    target_graduation_date: '2026-06-28',
    instructor_name: 'Elder Kofi Addo & Pastor David Osei-Tutu',
    status: 'graduated',
    notes: 'Graduated 28 new believers with full immersion water baptism and right hand of fellowship.',
    created_at: '2026-04-20T09:00:00.000Z',
  },
];

// ==========================================
// SAMPLE FOUNDATION SCHOOL STUDENTS
// ==========================================
export const sampleFoundationStudents: FoundationStudent[] = [
  {
    id: 'fnd-std-1',
    cohort_id: 'fnd-cohort-2026-b',
    cohort_name: 'Class of Faith & Power (Cohort 2026-B)',
    member_id: 'mem-4',
    member_name: 'Mercy Appiah',
    member_phone: '+233 24 555 1212',
    enrollment_date: '2026-09-06',
    completed_modules: [1, 2, 3, 4],
    water_baptism_status: true,
    water_baptism_date: '2026-09-20',
    status: 'in_progress',
    notes: 'Excelling in Module 4 (Evangelism); preparing for final doctrine defense and graduation.',
    created_at: '2026-09-06T11:00:00.000Z',
  },
  {
    id: 'fnd-std-2',
    cohort_id: 'fnd-cohort-2026-b',
    cohort_name: 'Class of Faith & Power (Cohort 2026-B)',
    member_id: 'mem-5',
    member_name: 'Benjamin Antwi',
    member_phone: '+233 24 777 6655',
    enrollment_date: '2026-09-06',
    completed_modules: [1, 2, 3],
    water_baptism_status: false,
    status: 'in_progress',
    notes: 'Scheduled for upcoming October water baptism immersion at Joma riverfront / sanctuary pool.',
    created_at: '2026-09-06T11:05:00.000Z',
  },
  {
    id: 'fnd-std-3',
    cohort_id: 'fnd-cohort-2026-b',
    cohort_name: 'Class of Faith & Power (Cohort 2026-B)',
    member_id: 'mem-2',
    member_name: 'Abena Serwaa',
    member_phone: '+233 20 333 4455',
    enrollment_date: '2026-09-06',
    completed_modules: [1, 2, 3, 4, 5],
    water_baptism_status: true,
    water_baptism_date: '2026-09-20',
    status: 'ready_for_baptism',
    notes: 'Completed all 5 curriculum modules! Ready for graduation ceremonies.',
    created_at: '2026-09-06T11:10:00.000Z',
  },
];



