import {
  Member,
  Visitor,
  ChurchService,
  AttendanceRecord,
  HeadcountRecord,
  GivingRecord,
  PledgeRecord,
  PledgeCampaign,
  ExpenseRecord,
  Ministry,
  SmallGroup,
  ChurchEvent,
  PastoralCareRecord,
  PrayerRequest,
  CommunicationRecord,
  AuditLog,
  ChurchSettings,
  UserProfile,
} from '../types/database.types';

export const initialSettings: ChurchSettings = {
  church_name: 'Greater Works City Church',
  branch_name: 'City of Refuge - Joma Central',
  tagline: 'Exceeding Abundantly Above All We Ask or Think (Ephesians 3:20)',
  short_name: 'GWCC',
  senior_pastor: 'Prophet Elisha K. Richard',
  general_secretary: 'Tamekloe Clara Gaewornu',
  logo_url: '/assets/logo.png',
  location: 'Joma New Site, Greater Accra, Ghana',
  address: 'Off Ablekuma-Joma Highway, Joma New Site',
  gps_address: 'GA-183-4921',
  phone: '+233 24 412 3456',
  email: 'info@greaterworkscitychurch.org',
  currency: 'GHS',
  currency_symbol: 'GH₵',
  timezone: 'Africa/Accra',
};

export const sampleUsers: UserProfile[] = [
  {
    id: 'usr-1',
    first_name: 'Elisha',
    last_name: 'Richard',
    email: 'prophet@greaterworkscitychurch.org',
    phone: '+233 24 412 3456',
    department: 'Pastoral Council',
    role: 'senior_pastor',
    is_active: true,
    created_at: '2025-01-01T08:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'usr-2',
    first_name: 'Clara',
    last_name: 'Gaewornu',
    email: 'secretary@greaterworkscitychurch.org',
    phone: '+233 20 890 1234',
    department: 'Church Administration',
    role: 'administrator',
    is_active: true,
    created_at: '2025-01-01T08:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'usr-3',
    first_name: 'Emmanuel',
    last_name: 'Osei',
    email: 'pastor.osei@greaterworkscitychurch.org',
    phone: '+233 24 987 6543',
    department: 'Pastoral Care & Music',
    role: 'pastor',
    is_active: true,
    created_at: '2025-01-01T08:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'usr-4',
    first_name: 'Akosua',
    last_name: 'Frimpong',
    email: 'finance@greaterworkscitychurch.org',
    phone: '+233 27 555 4321',
    department: 'Finance & Accounts',
    role: 'finance_officer',
    is_active: true,
    created_at: '2025-01-05T08:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'usr-5',
    first_name: 'Kwame',
    last_name: 'Mensah',
    email: 'ushering@greaterworkscitychurch.org',
    phone: '+233 24 333 8899',
    department: 'Ushers & Protocol',
    role: 'attendance_officer',
    is_active: true,
    created_at: '2025-02-01T08:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
  },
];

export const sampleMinistries: Ministry[] = [
  {
    id: 'min-1',
    name: 'Voice of Grace (Choir & Music)',
    description: 'Lead the congregation in prophetic praise, deep worship, and choral ministrations.',
    leader_name: 'Pastor Emmanuel Osei',
    meeting_schedule: 'Every Saturday at 4:00 PM',
    meeting_day: 'Saturday',
    meeting_time: '16:00',
    status: 'active',
    member_count: 24,
  },
  {
    id: 'min-2',
    name: "King's Ushers & Protocol",
    description: 'Ensure orderly sanctuary flow, warm visitor reception, and dignitary protocol during all church gatherings.',
    leader_name: 'Brother Kwame Mensah',
    meeting_schedule: 'Every Saturday at 5:30 PM',
    meeting_day: 'Saturday',
    meeting_time: '17:30',
    status: 'active',
    member_count: 18,
  },
  {
    id: 'min-3',
    name: 'Sound, Media & Broadcast',
    description: 'Sound engineering, live streaming on social platforms, digital recording, and multimedia projection.',
    leader_name: 'Brother Benjamin Antwi',
    meeting_schedule: 'Every Saturday at 3:00 PM',
    meeting_day: 'Saturday',
    meeting_time: '15:00',
    status: 'active',
    member_count: 12,
  },
  {
    id: 'min-4',
    name: "Kingdom Builders (Men's Fellowship)",
    description: 'Empowering Christian men through business mentorship, family leadership, and kingdom financing.',
    leader_name: 'Elder Kofi Addo',
    meeting_schedule: '1st Saturday of each month at 7:00 AM',
    meeting_day: 'Saturday',
    meeting_time: '07:00',
    status: 'active',
    member_count: 35,
  },
  {
    id: 'min-5',
    name: 'Virtuous Women Fellowship',
    description: 'Nurturing godly women, mothers, and young ladies in prayer, home building, and community charity.',
    leader_name: 'Deaconess Akosua Frimpong',
    meeting_schedule: '2nd Saturday of each month at 8:00 AM',
    meeting_day: 'Saturday',
    meeting_time: '08:00',
    status: 'active',
    member_count: 42,
  },
  {
    id: 'min-6',
    name: 'Chosen Generation (Youth & Campus)',
    description: 'Dynamic ministry for senior high, tertiary students, and young professionals discovering their destiny.',
    leader_name: 'Sister Abena Serwaa',
    meeting_schedule: 'Every Sunday at 1:00 PM',
    meeting_day: 'Sunday',
    meeting_time: '13:00',
    status: 'active',
    member_count: 38,
  },
  {
    id: 'min-7',
    name: 'Little Lights (Children & Sunday School)',
    description: 'Biblical foundation, creative arts, and age-graded Bible lessons for toddlers and young children.',
    leader_name: 'Sister Grace Ansah',
    meeting_schedule: 'Every Sunday during Main Service (8:30 AM)',
    meeting_day: 'Sunday',
    meeting_time: '08:30',
    status: 'active',
    member_count: 45,
  },
  {
    id: 'min-8',
    name: 'Evangelism & Welfare Outreach',
    description: 'Hospital visits, street evangelism, prison ministry, and welfare support for needy families.',
    leader_name: 'Brother Samuel Tetteh',
    meeting_schedule: '3rd Saturday of each month at 6:30 AM',
    meeting_day: 'Saturday',
    meeting_time: '06:30',
    status: 'active',
    member_count: 22,
  },
];

export const sampleSmallGroups: SmallGroup[] = [
  {
    id: 'sg-1',
    name: 'Joma Central Cell',
    leader_name: 'Elder Kofi Addo',
    leader_phone: '+233 24 111 2233',
    meeting_location: "Elder Kofi's Residence, Joma New Site",
    zone: 'Zone 1 - Joma Central',
    meeting_day: 'Tuesday',
    meeting_time: '18:30',
    member_count: 16,
  },
  {
    id: 'sg-2',
    name: 'Ablekuma Highway Fellowship',
    leader_name: 'Deaconess Akosua Frimpong',
    leader_phone: '+233 27 555 4321',
    meeting_location: 'Near Ablekuma Curve, Behind Fuel Station',
    zone: 'Zone 2 - Ablekuma Corridor',
    meeting_day: 'Tuesday',
    meeting_time: '19:00',
    member_count: 14,
  },
  {
    id: 'sg-3',
    name: 'Weija Hilltop Cell',
    leader_name: 'Brother Benjamin Antwi',
    leader_phone: '+233 24 777 6655',
    meeting_location: 'Weija Barrier Junction area',
    zone: 'Zone 3 - Weija & SCC',
    meeting_day: 'Tuesday',
    meeting_time: '18:30',
    member_count: 12,
  },
  {
    id: 'sg-4',
    name: 'Anyaa Market Fellowship',
    leader_name: 'Sister Abena Serwaa',
    leader_phone: '+233 20 333 4455',
    meeting_location: 'Anyaa Last Stop, Opposite Clinic',
    zone: 'Zone 4 - Anyaa & Awoshie',
    meeting_day: 'Tuesday',
    meeting_time: '19:00',
    member_count: 15,
  },
  {
    id: 'sg-5',
    name: 'Agape Home Fellowship',
    leader_name: 'Brother Samuel Tetteh',
    leader_phone: '+233 24 999 1122',
    meeting_location: 'Joma Top Town, Near Water Tower',
    zone: 'Zone 1 - Joma Central',
    meeting_day: 'Thursday',
    meeting_time: '18:30',
    member_count: 10,
  },
];

export const sampleServices: ChurchService[] = [
  {
    id: 'srv-1',
    name: 'Sunday Prophetic Celebration Service',
    type: 'sunday',
    day_of_week: 'Sunday',
    start_time: '08:30',
    end_time: '11:45',
    venue: 'City of Refuge Main Sanctuary, Joma',
    service_leader: 'Prophet Elisha K. Richard',
    preacher: 'Prophet Elisha K. Richard',
    worship_leader: 'Pastor Emmanuel Osei',
    expected_attendance: 250,
    description: 'Our flagship weekly celebration with deep prophetic praise, revelation preaching, healing, and prophetic declarations.',
    is_active: true,
  },
  {
    id: 'srv-2',
    name: 'Midweek Miracle & Breakthrough Encounter',
    type: 'midweek',
    day_of_week: 'Wednesday',
    start_time: '18:30',
    end_time: '20:30',
    venue: 'City of Refuge Main Sanctuary, Joma',
    service_leader: 'Pastor Emmanuel Osei',
    preacher: 'Prophet Elisha K. Richard',
    worship_leader: 'Sister Abena Serwaa',
    expected_attendance: 140,
    description: 'Intense teaching of the Word, practical faith warfare, communion, and special prayer ministration for believers.',
    is_active: true,
  },
  {
    id: 'srv-3',
    name: 'Prophetic Hour & All-Night Vigil',
    type: 'prayer',
    day_of_week: 'Friday',
    start_time: '22:00',
    end_time: '04:00',
    venue: 'City of Refuge Main Sanctuary, Joma',
    service_leader: 'Prophet Elisha K. Richard',
    preacher: 'Prophet Elisha K. Richard',
    worship_leader: 'Voice of Grace Praise Team',
    expected_attendance: 180,
    description: 'High-voltage night of intercession, spiritual warfare, family deliverance, and open heavens.',
    is_active: true,
  },
];

export const sampleMembers: Member[] = [
  {
    id: 'mem-1',
    member_id: 'GWCC-0001',
    tithe_number: 'T-1001',
    first_name: 'Kwame',
    last_name: 'Mensah',
    gender: 'male',
    date_of_birth: '1984-04-12',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Logistics Supervisor',
    employer: 'Accra Port Terminal Ltd',
    phone: '+233 24 333 8899',
    email: 'kwame.mensah@gmail.com',
    residential_address: 'House 42, Joma New Site',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-183-4901',
    status: 'leader',
    membership_date: '2023-01-15',
    baptism_status: true,
    baptism_date: '2023-03-20',
    baptized_by: 'Prophet Elisha K. Richard',
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-2',
    ministry_name: "King's Ushers & Protocol",
    small_group_id: 'sg-1',
    small_group_name: 'Joma Central Cell',
    leadership_position: 'Head of Protocol',
    spouse_name: 'Faustina Mensah',
    spouse_is_member: true,
    number_of_children: 3,
    national_id: 'GHA-712398412-1',
    preferred_communication: 'whatsapp',
    is_archived: false,
    created_at: '2023-01-15T10:00:00.000Z',
    updated_at: '2026-01-15T10:00:00.000Z',
  },
  {
    id: 'mem-2',
    member_id: 'GWCC-0002',
    tithe_number: 'T-1002',
    first_name: 'Akosua',
    last_name: 'Frimpong',
    gender: 'female',
    date_of_birth: '1988-09-23',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Chartered Accountant',
    employer: 'Universal Merchant Services',
    phone: '+233 27 555 4321',
    email: 'akosua.frimpong@outlook.com',
    residential_address: 'Plot 15, Ablekuma Highway',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-184-1122',
    status: 'leader',
    membership_date: '2023-02-10',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-5',
    ministry_name: 'Virtuous Women Fellowship',
    small_group_id: 'sg-2',
    small_group_name: 'Ablekuma Highway Fellowship',
    leadership_position: 'Finance Deaconess',
    spouse_name: 'Kwabena Frimpong',
    number_of_children: 2,
    national_id: 'GHA-829103841-4',
    preferred_communication: 'whatsapp',
    is_archived: false,
    created_at: '2023-02-10T10:00:00.000Z',
    updated_at: '2026-02-01T10:00:00.000Z',
  },
  {
    id: 'mem-3',
    member_id: 'GWCC-0003',
    tithe_number: 'T-1003',
    first_name: 'Kofi',
    last_name: 'Addo',
    gender: 'male',
    date_of_birth: '1976-11-05',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Civil Contractor',
    employer: 'Addo Infrastructure Ltd',
    phone: '+233 24 111 2233',
    email: 'elder.kofi.addo@gmail.com',
    residential_address: 'Near Old Chief Palace, Joma',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-183-5509',
    status: 'leader',
    membership_date: '2022-11-01',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-4',
    ministry_name: "Kingdom Builders (Men's Fellowship)",
    small_group_id: 'sg-1',
    small_group_name: 'Joma Central Cell',
    leadership_position: 'Presiding Elder',
    spouse_name: 'Evelyn Addo',
    spouse_is_member: true,
    number_of_children: 4,
    national_id: 'GHA-629104921-7',
    preferred_communication: 'call',
    is_archived: false,
    created_at: '2022-11-01T10:00:00.000Z',
    updated_at: '2026-01-20T10:00:00.000Z',
  },
  {
    id: 'mem-4',
    member_id: 'GWCC-0004',
    tithe_number: 'T-1004',
    first_name: 'Abena',
    last_name: 'Serwaa',
    gender: 'female',
    date_of_birth: '1995-07-18',
    marital_status: 'single',
    nationality: 'Ghanaian',
    occupation: 'Pharmacist',
    employer: 'Ridge Care Pharmacy, Anyaa',
    phone: '+233 20 333 4455',
    email: 'abena.serwaa@yahoo.com',
    residential_address: 'House 8B, Anyaa Market Road',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-190-2810',
    status: 'active',
    membership_date: '2023-04-14',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-6',
    ministry_name: 'Chosen Generation (Youth & Campus)',
    small_group_id: 'sg-4',
    small_group_name: 'Anyaa Market Fellowship',
    leadership_position: 'Youth President',
    national_id: 'GHA-910293849-0',
    preferred_communication: 'whatsapp',
    is_archived: false,
    created_at: '2023-04-14T10:00:00.000Z',
    updated_at: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'mem-5',
    member_id: 'GWCC-0005',
    tithe_number: 'T-1005',
    first_name: 'Benjamin',
    last_name: 'Antwi',
    gender: 'male',
    date_of_birth: '1992-02-28',
    marital_status: 'single',
    nationality: 'Ghanaian',
    occupation: 'Software & Network Engineer',
    employer: 'FinTech Hub Ghana',
    phone: '+233 24 777 6655',
    email: 'ben.antwi@techghana.com',
    residential_address: 'Hilltop View, Weija',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-210-9831',
    status: 'leader',
    membership_date: '2023-03-12',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-3',
    ministry_name: 'Sound, Media & Broadcast',
    small_group_id: 'sg-3',
    small_group_name: 'Weija Hilltop Cell',
    leadership_position: 'Media Director',
    national_id: 'GHA-789012345-2',
    preferred_communication: 'whatsapp',
    is_archived: false,
    created_at: '2023-03-12T10:00:00.000Z',
    updated_at: '2026-02-15T10:00:00.000Z',
  },
  {
    id: 'mem-6',
    member_id: 'GWCC-0006',
    tithe_number: 'T-1006',
    first_name: 'Grace',
    last_name: 'Ansah',
    gender: 'female',
    date_of_birth: '1989-12-14',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Senior High School Teacher',
    employer: 'Ghana Education Service',
    phone: '+233 50 123 9876',
    email: 'grace.ansah@gmail.com',
    residential_address: 'Estate Junction, Joma',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-183-6621',
    status: 'active',
    membership_date: '2023-05-20',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-7',
    ministry_name: 'Little Lights (Children & Sunday School)',
    small_group_id: 'sg-1',
    small_group_name: 'Joma Central Cell',
    leadership_position: 'Children Ministry Coordinator',
    spouse_name: 'Michael Ansah',
    number_of_children: 2,
    national_id: 'GHA-890123456-7',
    preferred_communication: 'sms',
    is_archived: false,
    created_at: '2023-05-20T10:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'mem-7',
    member_id: 'GWCC-0007',
    tithe_number: 'T-1007',
    first_name: 'Samuel',
    last_name: 'Tetteh',
    gender: 'male',
    date_of_birth: '1982-06-30',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Wholesale Food Merchant',
    employer: 'Self Employed',
    phone: '+233 24 999 1122',
    email: 'samuel.tetteh@tettehtrading.com',
    residential_address: 'Behind Joma Water Works',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-183-7744',
    status: 'leader',
    membership_date: '2023-06-08',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-8',
    ministry_name: 'Evangelism & Welfare Outreach',
    small_group_id: 'sg-5',
    small_group_name: 'Agape Home Fellowship',
    leadership_position: 'Outreach Director',
    spouse_name: 'Patience Tetteh',
    number_of_children: 3,
    national_id: 'GHA-678901234-5',
    preferred_communication: 'call',
    is_archived: false,
    created_at: '2023-06-08T10:00:00.000Z',
    updated_at: '2026-02-28T10:00:00.000Z',
  },
  {
    id: 'mem-8',
    member_id: 'GWCC-0008',
    tithe_number: 'T-1008',
    first_name: 'Faustina',
    last_name: 'Mensah',
    gender: 'female',
    date_of_birth: '1987-03-15',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Registered Midwife',
    employer: 'Ga South Municipal Hospital',
    phone: '+233 20 444 7711',
    email: 'faustina.mensah@gmail.com',
    residential_address: 'House 42, Joma New Site',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-183-4901',
    status: 'active',
    membership_date: '2023-01-15',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-5',
    ministry_name: 'Virtuous Women Fellowship',
    small_group_id: 'sg-1',
    small_group_name: 'Joma Central Cell',
    spouse_name: 'Kwame Mensah',
    spouse_is_member: true,
    number_of_children: 3,
    national_id: 'GHA-789123450-8',
    preferred_communication: 'whatsapp',
    is_archived: false,
    created_at: '2023-01-15T10:00:00.000Z',
    updated_at: '2026-01-15T10:00:00.000Z',
  },
  {
    id: 'mem-9',
    member_id: 'GWCC-0009',
    tithe_number: 'T-1009',
    first_name: 'David',
    last_name: 'Quaye',
    gender: 'male',
    date_of_birth: '1997-10-10',
    marital_status: 'single',
    nationality: 'Ghanaian',
    occupation: 'Graphic Designer & Videographer',
    employer: 'Creative Pixels Studio',
    phone: '+233 54 888 3322',
    email: 'dquaye.art@gmail.com',
    residential_address: 'Ablekuma Fan Milk Junction',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-184-7733',
    status: 'active',
    membership_date: '2024-01-21',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-3',
    ministry_name: 'Sound, Media & Broadcast',
    small_group_id: 'sg-2',
    small_group_name: 'Ablekuma Highway Fellowship',
    national_id: 'GHA-923456781-3',
    preferred_communication: 'whatsapp',
    is_archived: false,
    created_at: '2024-01-21T10:00:00.000Z',
    updated_at: '2026-02-10T10:00:00.000Z',
  },
  {
    id: 'mem-10',
    member_id: 'GWCC-0010',
    tithe_number: 'T-1010',
    first_name: 'Joyce',
    last_name: 'Boakye',
    gender: 'female',
    date_of_birth: '1993-08-04',
    marital_status: 'single',
    nationality: 'Ghanaian',
    occupation: 'Nurse Officer',
    employer: 'Korle Bu Polyclinic',
    phone: '+233 27 666 9900',
    email: 'joyce.boakye93@gmail.com',
    residential_address: 'SCC Barrier Area, Weija',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-210-4411',
    status: 'active',
    membership_date: '2024-03-10',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-1',
    ministry_name: 'Voice of Grace (Choir & Music)',
    small_group_id: 'sg-3',
    small_group_name: 'Weija Hilltop Cell',
    national_id: 'GHA-834567890-2',
    preferred_communication: 'whatsapp',
    is_archived: false,
    created_at: '2024-03-10T10:00:00.000Z',
    updated_at: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'mem-11',
    member_id: 'GWCC-0011',
    tithe_number: 'T-1011',
    first_name: 'Emmanuel',
    last_name: 'Osei',
    gender: 'male',
    date_of_birth: '1980-05-19',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'Associate Pastor / Music Director',
    employer: 'Greater Works City Church',
    phone: '+233 24 987 6543',
    email: 'pastor.osei@greaterworkscitychurch.org',
    residential_address: 'Pastoral Residence, Joma',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-183-4921',
    status: 'leader',
    membership_date: '2022-09-01',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-1',
    ministry_name: 'Voice of Grace (Choir & Music)',
    small_group_id: 'sg-1',
    small_group_name: 'Joma Central Cell',
    leadership_position: 'Associate Pastor & Music Director',
    spouse_name: 'Doris Osei',
    spouse_is_member: true,
    number_of_children: 3,
    national_id: 'GHA-610293847-5',
    preferred_communication: 'whatsapp',
    is_archived: false,
    created_at: '2022-09-01T10:00:00.000Z',
    updated_at: '2026-01-01T10:00:00.000Z',
  },
  {
    id: 'mem-12',
    member_id: 'GWCC-0012',
    tithe_number: 'T-1012',
    first_name: 'Clara',
    last_name: 'Gaewornu',
    gender: 'female',
    date_of_birth: '1986-11-25',
    marital_status: 'married',
    nationality: 'Ghanaian',
    occupation: 'General Secretary & Administrator',
    employer: 'Greater Works City Church',
    phone: '+233 20 890 1234',
    email: 'secretary@greaterworkscitychurch.org',
    residential_address: 'Gaewornu Villa, Joma New Site',
    city: 'Accra',
    region: 'Greater Accra',
    gps_address: 'GA-183-4950',
    status: 'leader',
    membership_date: '2022-08-15',
    baptism_status: true,
    salvation_status: true,
    membership_class_completed: true,
    ministry_id: 'min-2',
    ministry_name: "King's Ushers & Protocol",
    small_group_id: 'sg-1',
    small_group_name: 'Joma Central Cell',
    leadership_position: 'General Secretary',
    spouse_name: 'Kafui Gaewornu',
    number_of_children: 2,
    national_id: 'GHA-723456789-1',
    preferred_communication: 'whatsapp',
    is_archived: false,
    created_at: '2022-08-15T10:00:00.000Z',
    updated_at: '2026-01-05T10:00:00.000Z',
  },
];

export const sampleVisitors: Visitor[] = [
  {
    id: 'vis-1',
    full_name: 'Prince Daniel Kwarteng',
    gender: 'male',
    phone: '+233 55 123 7890',
    email: 'pkwarteng@gmail.com',
    address: 'Near Joma Taxi Rank',
    gps_address: 'GA-183-8812',
    visit_date: '2026-09-27',
    service_attended: 'Sunday Prophetic Celebration Service',
    invited_by: 'Brother Kwame Mensah',
    how_heard: 'Friend / Church Member',
    prayer_request: 'Breakthrough in interview for international maritime logistics job.',
    follow_up_status: 'returning_visitor',
    assigned_to: 'usr-5',
    assigned_to_name: 'Kwame Mensah',
    notes: 'Warm gentleman. Attended second service with enthusiasm. Expressed interest in joining the Protocol team.',
    created_at: '2026-09-27T12:00:00.000Z',
    updated_at: '2026-09-30T10:00:00.000Z',
  },
  {
    id: 'vis-2',
    full_name: 'Rita Serwaa Boateng',
    gender: 'female',
    phone: '+233 24 666 1234',
    email: 'rita.boateng@yahoo.com',
    address: 'Ablekuma Fan Milk, Near Shell',
    gps_address: 'GA-184-3321',
    visit_date: '2026-09-27',
    service_attended: 'Sunday Prophetic Celebration Service',
    invited_by: 'Church Banner along Highway',
    how_heard: 'Flyer / Banner',
    prayer_request: 'Divine healing for chronic migraines and peace in marriage.',
    follow_up_status: 'contacted',
    assigned_to: 'usr-4',
    assigned_to_name: 'Akosua Frimpong',
    notes: 'Contacted via WhatsApp on Tuesday. She appreciated the prayer and requested home visitation from Virtuous Women.',
    created_at: '2026-09-27T12:15:00.000Z',
    updated_at: '2026-09-29T14:30:00.000Z',
  },
  {
    id: 'vis-3',
    full_name: 'Joshua Nii Armah',
    gender: 'male',
    phone: '+233 20 777 9988',
    address: 'Weija SCC Junction',
    gps_address: 'GA-210-5566',
    visit_date: '2026-09-20',
    service_attended: 'Midweek Miracle Encounter',
    invited_by: 'Brother Benjamin Antwi',
    how_heard: 'Social Media / Facebook Live',
    prayer_request: 'Spiritual deliverance and clarity of purpose for university graduation.',
    follow_up_status: 'converted_to_member',
    assigned_to: 'usr-3',
    assigned_to_name: 'Emmanuel Osei',
    converted_to_member_id: 'mem-9',
    notes: 'Attended Foundation Class on Saturday. Now fully integrated into the Young Adults Fellowship.',
    created_at: '2026-09-20T20:30:00.000Z',
    updated_at: '2026-09-28T16:00:00.000Z',
  },
  {
    id: 'vis-4',
    full_name: 'Mercy Korkor Tetteh',
    gender: 'female',
    phone: '+233 54 990 0112',
    address: 'Anyaa Last Stop',
    gps_address: 'GA-190-7711',
    visit_date: '2026-09-25',
    service_attended: 'Prophetic Hour & All-Night Vigil',
    invited_by: 'Sister Abena Serwaa',
    how_heard: 'Friend / Church Member',
    prayer_request: 'Conception and fruit of the womb after 3 years of marriage.',
    follow_up_status: 'follow_up_required',
    assigned_to: 'usr-2',
    assigned_to_name: 'Clara Gaewornu',
    notes: 'Very touched by the midnight deliverance prayers. Requested pastoral counseling with Prophet Elisha.',
    created_at: '2026-09-26T04:30:00.000Z',
    updated_at: '2026-09-28T09:00:00.000Z',
  },
  {
    id: 'vis-5',
    full_name: 'Caleb Evans Cudjoe',
    gender: 'male',
    phone: '+233 24 555 8800',
    address: 'Joma Top Town',
    gps_address: 'GA-183-9900',
    visit_date: '2026-10-02',
    service_attended: 'Sunday Prophetic Celebration Service',
    how_heard: 'Personal Search / Passed By',
    prayer_request: 'Guidance and financial provision for family building project.',
    follow_up_status: 'new',
    assigned_to: 'usr-5',
    assigned_to_name: 'Kwame Mensah',
    notes: 'First time in Joma area, moved here 2 weeks ago from Kumasi. Warmly welcomed with visitor welcome pack.',
    created_at: '2026-10-02T11:00:00.000Z',
    updated_at: '2026-10-02T11:00:00.000Z',
  },
];

export const sampleHeadcounts: HeadcountRecord[] = [
  {
    id: 'hc-1',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-27',
    men: 68,
    women: 94,
    youth: 42,
    children: 38,
    visitors: 12,
    ushers_protocol: 16,
    online_viewers: 85,
    total_auditorium: 242,
    notes: 'Special Thanksgiving Sunday service. High attendance, additional overflow chairs set up.',
    counted_by: 'Brother Kwame Mensah',
    created_at: '2026-09-27T11:30:00.000Z',
  },
  {
    id: 'hc-2',
    service_id: 'srv-2',
    service_name: 'Midweek Miracle & Breakthrough Encounter',
    date: '2026-09-23',
    men: 34,
    women: 56,
    youth: 28,
    children: 16,
    visitors: 6,
    ushers_protocol: 8,
    online_viewers: 62,
    total_auditorium: 134,
    notes: 'Communion and healing service. Powerful impartation service.',
    counted_by: 'Brother Kwame Mensah',
    created_at: '2026-09-23T20:15:00.000Z',
  },
  {
    id: 'hc-3',
    service_id: 'srv-3',
    service_name: 'Prophetic Hour & All-Night Vigil',
    date: '2026-09-25',
    men: 52,
    women: 78,
    youth: 39,
    children: 12,
    visitors: 15,
    ushers_protocol: 12,
    online_viewers: 110,
    total_auditorium: 181,
    notes: 'Deliverance and night of open heavens. Over 110 concurrent online viewers on Facebook Live.',
    counted_by: 'Brother Kwame Mensah',
    created_at: '2026-09-26T03:45:00.000Z',
  },
  {
    id: 'hc-4',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-20',
    men: 64,
    women: 88,
    youth: 39,
    children: 35,
    visitors: 9,
    ushers_protocol: 14,
    online_viewers: 72,
    total_auditorium: 226,
    notes: 'Sermon on Exceeding Abundantly (Ephesians 3:20). 4 souls gave their lives to Christ.',
    counted_by: 'Brother Kwame Mensah',
    created_at: '2026-09-20T11:30:00.000Z',
  },
];

export const sampleAttendance: AttendanceRecord[] = [
  {
    id: 'att-1',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-27',
    member_id: 'mem-1',
    member_name: 'Kwame Mensah',
    person_name: 'Kwame Mensah',
    person_type: 'member',
    check_in_time: '08:15',
    check_in_method: 'qr_code',
    status: 'present',
    recorded_by: 'System Kiosk',
  },
  {
    id: 'att-2',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-27',
    member_id: 'mem-2',
    member_name: 'Akosua Frimpong',
    person_name: 'Akosua Frimpong',
    person_type: 'member',
    check_in_time: '08:20',
    check_in_method: 'mobile',
    status: 'present',
    recorded_by: 'System Kiosk',
  },
  {
    id: 'att-3',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-27',
    member_id: 'mem-3',
    member_name: 'Kofi Addo',
    person_name: 'Kofi Addo',
    person_type: 'member',
    check_in_time: '08:10',
    check_in_method: 'search',
    status: 'present',
    recorded_by: 'Brother Kwame Mensah',
  },
  {
    id: 'att-4',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-27',
    member_id: 'mem-4',
    member_name: 'Abena Serwaa',
    person_name: 'Abena Serwaa',
    person_type: 'member',
    check_in_time: '08:25',
    check_in_method: 'qr_code',
    status: 'present',
    recorded_by: 'System Kiosk',
  },
  {
    id: 'att-5',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-27',
    member_id: 'mem-5',
    member_name: 'Benjamin Antwi',
    person_name: 'Benjamin Antwi',
    person_type: 'member',
    check_in_time: '07:45',
    check_in_method: 'manual',
    status: 'present',
    recorded_by: 'Brother Kwame Mensah',
  },
  {
    id: 'att-6',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-27',
    member_id: 'mem-6',
    member_name: 'Grace Ansah',
    person_name: 'Grace Ansah',
    person_type: 'member',
    check_in_time: '08:22',
    check_in_method: 'search',
    status: 'present',
    recorded_by: 'Brother Kwame Mensah',
  },
  {
    id: 'att-7',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-27',
    visitor_id: 'vis-1',
    visitor_name: 'Prince Daniel Kwarteng',
    person_name: 'Prince Daniel Kwarteng',
    person_type: 'visitor',
    check_in_time: '08:35',
    check_in_method: 'manual',
    status: 'present',
    recorded_by: 'Brother Kwame Mensah',
  },
  {
    id: 'att-8',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    date: '2026-09-27',
    visitor_id: 'vis-2',
    visitor_name: 'Rita Serwaa Boateng',
    person_name: 'Rita Serwaa Boateng',
    person_type: 'visitor',
    check_in_time: '08:40',
    check_in_method: 'manual',
    status: 'present',
    recorded_by: 'Brother Kwame Mensah',
  },
];

export const sampleGiving: GivingRecord[] = [
  {
    id: 'giv-1',
    member_id: 'mem-3',
    member_name: 'Kofi Addo',
    donor_name: 'Elder Kofi Addo',
    category: 'Tithe',
    amount: 1200,
    currency: 'GHS',
    date: '2026-09-27',
    payment_method: 'mobile_money',
    payment_channel: 'MTN MoMo',
    reference_number: 'MOMO-72910482',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    notes: 'September Business Tithe',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-27T11:45:00.000Z',
  },
  {
    id: 'giv-2',
    member_id: 'mem-2',
    member_name: 'Akosua Frimpong',
    donor_name: 'Akosua Frimpong',
    category: 'Tithe',
    amount: 850,
    currency: 'GHS',
    date: '2026-09-27',
    payment_method: 'bank_transfer',
    payment_channel: 'Ecobank Ghana',
    reference_number: 'ECO-9921048',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    notes: 'September Monthly Tithe',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-27T11:46:00.000Z',
  },
  {
    id: 'giv-3',
    donor_name: 'Congregational General Collection',
    category: 'Offering',
    amount: 2840,
    currency: 'GHS',
    date: '2026-09-27',
    payment_method: 'cash',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    notes: 'Sunday First & Second General Offering combined count',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-27T12:00:00.000Z',
  },
  {
    id: 'giv-4',
    member_id: 'mem-1',
    member_name: 'Kwame Mensah',
    donor_name: 'Kwame Mensah',
    category: 'Building Fund',
    amount: 500,
    currency: 'GHS',
    date: '2026-09-27',
    payment_method: 'mobile_money',
    payment_channel: 'Telecel Cash',
    reference_number: 'TEL-8831092',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    notes: 'Cathedral Sanctuary Expansion contribution',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-27T11:50:00.000Z',
  },
  {
    id: 'giv-5',
    member_id: 'mem-4',
    member_name: 'Abena Serwaa',
    donor_name: 'Abena Serwaa',
    category: 'Tithe',
    amount: 600,
    currency: 'GHS',
    date: '2026-09-27',
    payment_method: 'mobile_money',
    payment_channel: 'MTN MoMo',
    reference_number: 'MOMO-3391820',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    notes: 'Faithful Tithe',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-27T11:52:00.000Z',
  },
  {
    id: 'giv-6',
    member_id: 'mem-5',
    member_name: 'Benjamin Antwi',
    donor_name: 'Benjamin Antwi',
    category: 'Seed',
    amount: 750,
    currency: 'GHS',
    date: '2026-09-25',
    payment_method: 'mobile_money',
    payment_channel: 'MTN MoMo',
    reference_number: 'MOMO-4401928',
    service_id: 'srv-3',
    service_name: 'Prophetic Hour & All-Night Vigil',
    notes: 'All-Night Prophetic Altar Seed for project victory',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-26T02:00:00.000Z',
  },
  {
    id: 'giv-7',
    member_id: 'mem-7',
    member_name: 'Samuel Tetteh',
    donor_name: 'Samuel Tetteh',
    category: 'Thanksgiving',
    amount: 1500,
    currency: 'GHS',
    date: '2026-09-20',
    payment_method: 'cash',
    service_id: 'srv-1',
    service_name: 'Sunday Prophetic Celebration Service',
    notes: 'Special Thanksgiving for new delivery van purchase',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-20T11:40:00.000Z',
  },
];

export const sampleCampaigns: PledgeCampaign[] = [
  {
    id: 'camp-1',
    name: 'Cathedral Sanctuary Expansion 2026',
    target_amount: 250000,
    start_date: '2026-01-01',
    end_date: '2026-12-31',
    description: 'Procurement of structural steel framing, auditorium roofing, and acoustic insulation for the main auditorium expansion.',
    is_active: true,
  },
  {
    id: 'camp-2',
    name: 'Media & Sound Modernization Project',
    target_amount: 60000,
    start_date: '2026-05-01',
    end_date: '2026-11-30',
    description: 'Digital 32-channel sound console, wireless vocal microphones, 4K broadcast cameras, and streaming encoders.',
    is_active: true,
  },
];

export const samplePledges: PledgeRecord[] = [
  {
    id: 'pld-1',
    campaign_id: 'camp-1',
    campaign_name: 'Cathedral Sanctuary Expansion 2026',
    member_id: 'mem-3',
    member_name: 'Kofi Addo',
    member_phone: '+233 24 111 2233',
    amount_pledged: 15000,
    amount_paid: 10000,
    balance: 5000,
    start_date: '2026-02-01',
    due_date: '2026-11-30',
    status: 'partially_paid',
    notes: 'GH₵ 5,000 paid via MoMo in April, GH₵ 5,000 paid in August.',
    created_at: '2026-02-01T10:00:00.000Z',
    updated_at: '2026-08-15T10:00:00.000Z',
  },
  {
    id: 'pld-2',
    campaign_id: 'camp-1',
    campaign_name: 'Cathedral Sanctuary Expansion 2026',
    member_id: 'mem-2',
    member_name: 'Akosua Frimpong',
    member_phone: '+233 27 555 4321',
    amount_pledged: 8000,
    amount_paid: 8000,
    balance: 0,
    start_date: '2026-02-15',
    due_date: '2026-09-30',
    status: 'completed',
    notes: 'Pledge fully honored! Official receipt issued.',
    created_at: '2026-02-15T10:00:00.000Z',
    updated_at: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'pld-3',
    campaign_id: 'camp-2',
    campaign_name: 'Media & Sound Modernization Project',
    member_id: 'mem-5',
    member_name: 'Benjamin Antwi',
    member_phone: '+233 24 777 6655',
    amount_pledged: 5000,
    amount_paid: 3500,
    balance: 1500,
    start_date: '2026-05-10',
    due_date: '2026-10-31',
    status: 'partially_paid',
    notes: 'Media team leader pledge towards digital console.',
    created_at: '2026-05-10T10:00:00.000Z',
    updated_at: '2026-09-12T10:00:00.000Z',
  },
  {
    id: 'pld-4',
    campaign_id: 'camp-1',
    campaign_name: 'Cathedral Sanctuary Expansion 2026',
    member_id: 'mem-1',
    member_name: 'Kwame Mensah',
    member_phone: '+233 24 333 8899',
    amount_pledged: 4000,
    amount_paid: 2000,
    balance: 2000,
    start_date: '2026-03-01',
    due_date: '2026-12-15',
    status: 'partially_paid',
    notes: 'Monthly installments of GH₵ 500.',
    created_at: '2026-03-01T10:00:00.000Z',
    updated_at: '2026-09-27T12:00:00.000Z',
  },
  {
    id: 'pld-5',
    campaign_id: 'camp-2',
    campaign_name: 'Media & Sound Modernization Project',
    member_id: 'mem-9',
    member_name: 'David Quaye',
    member_phone: '+233 54 888 3322',
    amount_pledged: 2500,
    amount_paid: 2500,
    balance: 0,
    start_date: '2026-06-01',
    due_date: '2026-09-15',
    status: 'completed',
    notes: 'Fully redeemed in two installments.',
    created_at: '2026-06-01T10:00:00.000Z',
    updated_at: '2026-09-15T10:00:00.000Z',
  },
];

export const sampleExpenses: ExpenseRecord[] = [
  {
    id: 'exp-1',
    category: 'Utilities & Power',
    title: 'Electricity Company of Ghana (ECG) Bill',
    recipient: 'ECG Prepayment Depot, Ablekuma',
    amount: 1450,
    currency: 'GHS',
    date: '2026-09-24',
    account: 'Operations Account',
    payment_method: 'mobile_money',
    reference_number: 'ECG-771920',
    description: 'Prepaid power credit replenishment for main sanctuary air conditioning and floodlights.',
    approved_by: 'Prophet Elisha K. Richard',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-24T14:00:00.000Z',
  },
  {
    id: 'exp-2',
    category: 'Maintenance & Facility',
    title: 'Diesel Generator Fuel & Oil Service',
    recipient: 'TotalEnergies Ablekuma Highway',
    amount: 1200,
    currency: 'GHS',
    date: '2026-09-22',
    account: 'Operations Account',
    payment_method: 'cash',
    description: '100 Litres diesel fuel purchase and synthetic engine oil filter change for standby 65kVA generator.',
    approved_by: 'Elder Kofi Addo',
    recorded_by: 'Brother Kwame Mensah',
    created_at: '2026-09-22T10:30:00.000Z',
  },
  {
    id: 'exp-3',
    category: 'Welfare & Charity',
    title: 'Widows & Vulnerable Families Food Support',
    recipient: 'GWCC Welfare Committee',
    amount: 1800,
    currency: 'GHS',
    date: '2026-09-18',
    account: 'Welfare Account',
    payment_method: 'mobile_money',
    reference_number: 'WEL-551902',
    description: 'Monthly welfare packages (rice bags, cooking oil, canned fish) for 12 elderly widows and single mothers in Joma community.',
    approved_by: 'Prophet Elisha K. Richard',
    recorded_by: 'Brother Samuel Tetteh',
    created_at: '2026-09-18T16:00:00.000Z',
  },
  {
    id: 'exp-4',
    category: 'Media & Technology',
    title: 'High-Speed Fiber Internet Subscription',
    recipient: 'Telecel Ghana Broadband',
    amount: 650,
    currency: 'GHS',
    date: '2026-09-05',
    account: 'Operations Account',
    payment_method: 'bank_transfer',
    reference_number: 'TEL-441098',
    description: 'Monthly unlimited church dedicated fiber internet for Sunday and midweek online livestreaming.',
    approved_by: 'Prophet Elisha K. Richard',
    recorded_by: 'Deaconess Akosua Frimpong',
    created_at: '2026-09-05T09:00:00.000Z',
  },
];

export const sampleEvents: ChurchEvent[] = [
  {
    id: 'evt-1',
    title: 'Annual Greater Works Prophetic Convention 2026',
    description: 'Three nights and one grand Sunday of supernatural encounters, prophetic insight, and financial unction.',
    theme: 'Exceeding Abundantly (Ephesians 3:20)',
    theme_scripture: 'Ephesians 3:20',
    event_type: 'conference',
    start_date: '2026-10-21',
    end_date: '2026-10-25',
    start_time: '18:00',
    end_time: '21:30',
    venue: 'City of Refuge Main Sanctuary, Joma',
    organizer: 'General Church Council',
    speaker: 'Prophet Elisha K. Richard & Guest Apostles',
    expected_attendance: 450,
    budget: 35000,
    status: 'upcoming',
    requires_registration: true,
    registration_count: 85,
    banner_color: '#065f46',
    created_at: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'evt-2',
    title: 'Community Free Health Screening & Gospel Crusade',
    description: 'Free blood pressure checks, diabetes screening, doctor consultations, and open-air gospel proclamation in Joma market square.',
    theme: 'Healing for the Nations',
    event_type: 'community_outreach',
    start_date: '2026-10-10',
    end_date: '2026-10-10',
    start_time: '08:00',
    end_time: '15:00',
    venue: 'Joma Community Market Square',
    organizer: 'Evangelism & Welfare Ministry',
    speaker: 'Pastor Emmanuel Osei',
    expected_attendance: 300,
    budget: 8500,
    status: 'upcoming',
    requires_registration: false,
    banner_color: '#0284c7',
    created_at: '2026-09-10T10:00:00.000Z',
  },
  {
    id: 'evt-3',
    title: 'Night of Open Heavens & Prophetic Deliverance',
    description: 'All-night spiritual warfare, prophetic breakings of ancestral yokes, and divine empowerment.',
    theme: 'Loose Him and Let Him Go',
    event_type: 'all_night',
    start_date: '2026-10-30',
    end_date: '2026-10-31',
    start_time: '22:00',
    end_time: '04:30',
    venue: 'City of Refuge Main Sanctuary, Joma',
    organizer: 'Pastoral Council',
    speaker: 'Prophet Elisha K. Richard',
    expected_attendance: 250,
    budget: 4500,
    status: 'upcoming',
    requires_registration: false,
    banner_color: '#4f46e5',
    created_at: '2026-09-15T10:00:00.000Z',
  },
];

export const samplePastoralCare: PastoralCareRecord[] = [
  {
    id: 'pc-1',
    member_id: 'mem-1',
    member_name: 'Kwame Mensah',
    member_phone: '+233 24 333 8899',
    date: '2026-09-22',
    care_type: 'home_visit',
    pastor_name: 'Prophet Elisha K. Richard',
    assigned_pastor: 'Prophet Elisha K. Richard',
    notes: 'Pastoral home visitation and family prayer dedication for the Mensah household. Dedicated their new home addition to God in prayer.',
    action_items: 'Follow up in two weeks regarding family cell attendance.',
    status: 'completed',
    is_confidential: false,
    created_at: '2026-09-22T17:00:00.000Z',
  },
  {
    id: 'pc-2',
    member_id: 'mem-4',
    member_name: 'Abena Serwaa',
    member_phone: '+233 20 333 4455',
    date: '2026-09-15',
    care_type: 'counseling',
    pastor_name: 'Pastor Emmanuel Osei',
    assigned_pastor: 'Pastor Emmanuel Osei',
    notes: 'Career and ministry balance counseling. Encouraged her to continue leading the youth fellowship with joy and structured delegation.',
    status: 'completed',
    is_confidential: true,
    created_at: '2026-09-15T15:30:00.000Z',
  },
  {
    id: 'pc-3',
    member_id: 'mem-6',
    member_name: 'Grace Ansah',
    member_phone: '+233 50 123 9876',
    date: '2026-09-28',
    care_type: 'new_birth',
    pastor_name: 'Pastor Emmanuel Osei',
    assigned_pastor: 'Pastor Emmanuel Osei',
    notes: 'Baby dedication counseling for sister Grace Ansah and husband Michael Ansah. Preparation for dedication service in November.',
    action_items: 'Schedule baby dedication on the first Sunday of November 2026.',
    status: 'in_progress',
    is_confidential: false,
    created_at: '2026-09-28T16:00:00.000Z',
  },
];

export const samplePrayerRequests: PrayerRequest[] = [
  {
    id: 'pr-1',
    member_id: 'mem-7',
    requester_name: 'Samuel Tetteh',
    requester_phone: '+233 24 999 1122',
    category: 'Business & Finance',
    request: 'Pray for favorable terms on long-term agricultural wholesale supply contract with supermarket chains in Accra.',
    date_submitted: '2026-09-26',
    assigned_leader: 'Prophet Elisha K. Richard',
    status: 'praying',
    is_confidential: false,
    created_at: '2026-09-26T08:00:00.000Z',
  },
  {
    id: 'pr-2',
    member_id: 'mem-8',
    requester_name: 'Faustina Mensah',
    requester_phone: '+233 20 444 7711',
    category: 'Healing & Health',
    request: 'Thanksgiving to God! Mother who was hospitalized with respiratory distress has been discharged safely.',
    date_submitted: '2026-09-20',
    assigned_leader: 'Pastor Emmanuel Osei',
    status: 'answered',
    testimony: 'Doctors confirmed complete recovery without needing surgical intervention. God has shown Himself faithful!',
    is_confidential: false,
    created_at: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'pr-3',
    requester_name: 'Prince Daniel Kwarteng',
    requester_phone: '+233 55 123 7890',
    category: 'Job & Employment',
    request: 'Praying for success in upcoming job assessment with the Maritime Authority. Trusting God for divine favor.',
    date_submitted: '2026-09-27',
    assigned_leader: 'Brother Kwame Mensah',
    status: 'praying',
    is_confidential: false,
    created_at: '2026-09-27T12:00:00.000Z',
  },
];

export const sampleCommunications: CommunicationRecord[] = [
  {
    id: 'com-1',
    title: 'Sunday Prophetic Celebration Reminder',
    channel: 'sms',
    recipient_type: 'all_members',
    recipient_count: 142,
    message: 'Shalom Beloved of Greater Works City Church! Join us tomorrow Sunday at 8:30 AM for a glorious Prophetic Celebration Service. Your miracle awaits you. Ephesians 3:20.',
    sender_id: 'usr-2',
    status: 'sent',
    sent_at: '2026-09-26T18:00:00.000Z',
    created_by: 'Clara Gaewornu',
  },
  {
    id: 'com-2',
    title: 'Midweek Miracle Encounter Broadcast',
    channel: 'whatsapp',
    recipient_type: 'all_members',
    recipient_count: 156,
    message: 'Greetings in Christ! It is Wednesday Miracle Encounter at 6:30 PM. Come fasting and expecting divine intervention in every stubborn battle. Main Sanctuary, Joma.',
    sender_id: 'usr-2',
    status: 'sent',
    sent_at: '2026-09-23T14:00:00.000Z',
    created_by: 'Clara Gaewornu',
  },
];

export const sampleAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    user_name: 'Prophet Elisha K. Richard',
    user_role: 'senior_pastor',
    action: 'SYSTEM_INITIALIZATION',
    module: 'System',
    details: 'GWCC ChMS instance initialized with full church configuration and ministerial data.',
    timestamp: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'log-2',
    user_name: 'Deaconess Akosua Frimpong',
    user_role: 'finance_officer',
    action: 'RECORD_GIVING',
    module: 'Finance',
    record_id: 'giv-1',
    details: 'Recorded Tithe of GH₵ 1,200.00 from Elder Kofi Addo via MTN MoMo.',
    timestamp: '2026-09-27T11:45:00.000Z',
  },
  {
    id: 'log-3',
    user_name: 'Brother Kwame Mensah',
    user_role: 'attendance_officer',
    action: 'RECORD_HEADCOUNT',
    module: 'Attendance',
    record_id: 'hc-1',
    details: 'Submitted Sunday service headcount: 242 total auditorium attendees.',
    timestamp: '2026-09-27T11:30:00.000Z',
  },
];
